<a href="https://colab.research.google.com/github/Leonanda1013/DataLoverz/blob/main/Competition/Arkavidia/Arkavidia_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
kolom_penting = [
    'pm10',
    'so2',
    'co',
    'o3',
    'no2'
]

In [4]:
kolom_numerik_pm25 = [
    'pm10', 'pm25', 'co', 'o3', 'so2', 'no2', 'max'
]

kolom_numerik = [
    'pm10', 'co', 'o3', 'so2', 'no2', 'max'
]

In [5]:
# kategorik
kolom_kategori = ['stasiun', 'critical', 'kategori']

In [6]:
def clean_kolom_kategori(df, kolom_kategori):
    kolom = [c for c in kolom_kategori if c in df.columns]

    for col in kolom:
        df[col] = (
            df[col]
            .astype(str)
            .str.strip()
            .str.upper()
        )

    df[kolom] = df[kolom].astype('category')
    return df

# Lihat Info Kolom

In [7]:
ISPU1 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-2023-komponen-data.csv')
ISPU1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   periode_data               1825 non-null   int64
 1   tanggal                    1825 non-null   object
 2   stasiun                    1825 non-null   object
 3   pm_sepuluh                 1825 non-null   object
 4   pm_duakomalima             1825 non-null   object
 5   sulfur_dioksida            1825 non-null   object
 6   karbon_monoksida           1825 non-null   object
 7   ozon                       1825 non-null   object
 8   nitrogen_dioksida          1825 non-null   object
 9   max                        1825 non-null   object
 10  parameter_pencemar_kritis  1812 non-null   object
 11  kategori                   1825 non-null   object
dtypes: int64(1), object(11)
memory usage: 171.2+ KB

In [8]:
ISPU1

,periode_data,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202302,2023-02-25,DKI5 Kebon Jeruk Jakarta Barat,35,-,13,12,31,18,35,PM10,BAIK
1,202302,2023-02-26,DKI5 Kebon Jeruk Jakarta Barat,23,-,14,9,32,11,32,O3,BAIK
2,202302,2023-02-27,DKI5 Kebon Jeruk Jakarta Barat,20,-,13,8,33,13,33,O3,BAIK
3,202302,2023-02-28,DKI5 Kebon Jeruk Jakarta Barat,30,-,21,11,28,18,30,PM10,BAIK
4,202303,2023-03-01,DKI1 Bunderan HI,38,44,50,8,19,27,50,3,BAIK
...,...,...,...,...,...,...,...,...,...,...,...,...
1820,202311,2023-11-26,DKI5 Kebon Jeruk,48,71,33,21,44,20,71,PM25,SEDANG
1821,202311,2023-11-27,DKI5 Kebon Jeruk,51,76,32,18,53,19,76,PM25,SEDANG
1822,202311,2023-11-28,DKI5 Kebon Jeruk,56,88,33,20,48,21,88,PM25,SEDANG
1823,202311,2023-11-29,DKI5 Kebon Jeruk,56,88,32,18,56,18,88,PM25,SEDANG
1824,202311,2023-11-30,DKI5 Kebon Jeruk,30,57,32,15,61,17,61,O3,SEDANG

In [9]:
ISPU2 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-komponen-data-2024.csv')
ISPU2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   periode_data               1830 non-null   int64
 1   bulan                      1830 non-null   int64
 2   tanggal                    1830 non-null   int64
 3   stasiun                    1830 non-null   object
 4   pm_sepuluh                 1718 non-null   float64
 5   pm_duakomalima             1810 non-null   float64
 6   sulfur_dioksida            1821 non-null   float64
 7   karbon_monoksida           1818 non-null   float64
 8   ozon                       1821 non-null   float64
 9   nitrogen_dioksida          1804 non-null   float64
 10  max                        1825 non-null   float64
 11  parameter_pencemar_kritis  1784 non-null   object
 12  kategori                   1830 non-null   object
dtypes: float64(7), int64(3), object(3)
memory usage: 186.0+ KB

In [10]:
ISPU2

,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202401,1,21,DKI3 Jagakarsa,51.0,65.0,45.0,9.0,8.0,79.0,79.0,NaN,SEDANG
1,202401,1,22,DKI3 Jagakarsa,27.0,34.0,45.0,5.0,8.0,56.0,56.0,NaN,SEDANG
2,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0,PM25,SEDANG
3,202401,1,24,DKI3 Jagakarsa,46.0,65.0,46.0,8.0,9.0,38.0,65.0,PM25,SEDANG
4,202401,1,25,DKI3 Jagakarsa,37.0,55.0,47.0,7.0,11.0,28.0,55.0,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1825,202412,12,27,DKI5 Kebon Jeruk Jakarta Barat,NaN,55.0,27.0,9.0,30.0,12.0,55.0,PM25,SEDANG
1826,202412,12,28,DKI5 Kebon Jeruk Jakarta Barat,NaN,40.0,26.0,6.0,30.0,12.0,40.0,PM25,BAIK
1827,202412,12,29,DKI5 Kebon Jeruk Jakarta Barat,NaN,51.0,32.0,8.0,28.0,11.0,51.0,PM25,SEDANG
1828,202412,12,30,DKI5 Kebon Jeruk Jakarta Barat,NaN,34.0,9.0,5.0,38.0,8.0,38.0,O3,BAIK
1829,202412,12,31,DKI5 Kebon Jeruk Jakarta Barat,NaN,26.0,9.0,3.0,26.0,3.0,26.0,PM25,BAIK

In [284]:
ISPU2['stasiun'].unique()

array(['DKI3 Jagakarsa', 'DKI1 Bunderan HI', 'DKI2 Kelapa Gading',
       'DKI4 Lubang Buaya', 'DKI1 Bundaran Hotel Indonesia (HI)',
       'DKI5 Kebon Jeruk Jakarta Barat', 'DKI5 Kebon Jeruk'], dtype=object)

In [11]:
ISPU3 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-komponen-data-2025.csv')
ISPU3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   periode_data               1215 non-null   int64
 1   bulan                      1215 non-null   int64
 2   tanggal                    1215 non-null   int64
 3   stasiun                    1215 non-null   object
 4   pm_sepuluh                 1141 non-null   float64
 5   pm_duakomalima             1182 non-null   float64
 6   sulfur_dioksida            1171 non-null   float64
 7   karbon_monoksida           1183 non-null   float64
 8   ozon                       1181 non-null   float64
 9   nitrogen_dioksida          1175 non-null   float64
 10  max                        1213 non-null   float64
 11  parameter_pencemar_kritis  1199 non-null   object
 12  kategori                   1215 non-null   object
dtypes: float64(7), int64(3), object(3)
memory usage: 123.5+ KB

In [12]:
ISPU4 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2010-komponen-data.csv')
ISPU4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1825 non-null   int64
 1   tanggal       1825 non-null   object
 2   stasiun       1825 non-null   object
 3   pm10          1825 non-null   object
 4   so2           1825 non-null   object
 5   co            1825 non-null   object
 6   o3            1825 non-null   object
 7   no2           1825 non-null   object
 8   max           1825 non-null   int64
 9   critical      523 non-null    object
 10  categori      1825 non-null   object
dtypes: int64(2), object(9)
memory usage: 157.0+ KB

In [13]:
ISPU5 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2011-komponen-data.csv')
ISPU5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    object
 2   pm10          365 non-null    int64
 3   so2           365 non-null    int64
 4   co            365 non-null    int64
 5   o3            365 non-null    int64
 6   no2           365 non-null    int64
 7   max           365 non-null    int64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: int64(7), object(4)
memory usage: 31.5+ KB

In [14]:
ISPU6 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2012-komponen-data.csv')
ISPU6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  366 non-null    int64
 1   tanggal       366 non-null    object
 2   pm10          366 non-null    int64
 3   so2           366 non-null    int64
 4   co            366 non-null    int64
 5   o3            366 non-null    int64
 6   no2           366 non-null    int64
 7   max           366 non-null    int64
 8   critical      366 non-null    object
 9   categori      366 non-null    object
 10  lokasi_spku   366 non-null    object
dtypes: int64(7), object(4)
memory usage: 31.6+ KB

In [15]:
ISPU7 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2013-komponen-data.csv')
ISPU7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    object
 2   pm10          365 non-null    int64
 3   so2           365 non-null    int64
 4   co            365 non-null    int64
 5   o3            365 non-null    int64
 6   no2           365 non-null    int64
 7   max           365 non-null    int64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: int64(7), object(4)
memory usage: 31.5+ KB

In [16]:
ISPU8 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2014-komponen-data.csv')
ISPU8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1825 non-null   int64
 1   tanggal       1825 non-null   object
 2   stasiun       1825 non-null   object
 3   pm10          1825 non-null   object
 4   so2           1825 non-null   object
 5   co            1825 non-null   object
 6   o3            1825 non-null   object
 7   no2           1825 non-null   object
 8   max           1825 non-null   int64
 9   critical      1791 non-null   object
 10  categori      1825 non-null   object
dtypes: int64(2), object(9)
memory usage: 157.0+ KB

In [17]:
ISPU9 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2015-komponen-data.csv')
ISPU9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    object
 2   pm10          365 non-null    int64
 3   so2           365 non-null    int64
 4   co            365 non-null    int64
 5   o3            365 non-null    int64
 6   no2           365 non-null    int64
 7   max           365 non-null    int64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: int64(7), object(4)
memory usage: 31.5+ KB

In [18]:
ISPU10 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2016-komponen-data.csv')
ISPU10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1830 non-null   int64
 1   tanggal       1830 non-null   object
 2   stasiun       1830 non-null   object
 3   pm10          1830 non-null   object
 4   so2           1830 non-null   object
 5   co            1830 non-null   object
 6   o3            1830 non-null   object
 7   no2           1830 non-null   object
 8   max           1830 non-null   int64
 9   critical      1793 non-null   object
 10  categori      1830 non-null   object
dtypes: int64(2), object(9)
memory usage: 157.4+ KB

In [19]:
ISPU11 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2017-komponen-data.csv')
ISPU11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1825 non-null   int64
 1   tanggal       1825 non-null   object
 2   stasiun       1825 non-null   object
 3   pm10          1825 non-null   object
 4   so2           1825 non-null   object
 5   co            1825 non-null   object
 6   o3            1825 non-null   object
 7   no2           1825 non-null   object
 8   max           1825 non-null   object
 9   critical      1800 non-null   object
 10  categori      1825 non-null   object
dtypes: int64(1), object(10)
memory usage: 157.0+ KB

In [20]:
ISPU12 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2018-komponen-data.csv')
ISPU12.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    object
 2   pm10          365 non-null    int64
 3   so2           365 non-null    int64
 4   co            365 non-null    int64
 5   o3            365 non-null    int64
 6   no2           365 non-null    int64
 7   max           365 non-null    int64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: int64(7), object(4)
memory usage: 31.5+ KB

In [21]:
ISPU13 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2019-komponen-data.csv')
ISPU13.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  345 non-null    int64
 1   tanggal       345 non-null    object
 2   pm10          345 non-null    int64
 3   so2           345 non-null    int64
 4   co            345 non-null    int64
 5   o3            345 non-null    int64
 6   no2           345 non-null    int64
 7   max           345 non-null    int64
 8   critical      345 non-null    object
 9   categori      345 non-null    object
 10  lokasi_spku   345 non-null    object
dtypes: int64(7), object(4)
memory usage: 29.8+ KB

In [22]:
ISPU14 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2020-komponen-data.csv')
ISPU14.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  366 non-null    int64
 1   tanggal       366 non-null    object
 2   pm10          366 non-null    int64
 3   so2           366 non-null    object
 4   co            366 non-null    object
 5   o3            366 non-null    int64
 6   no2           366 non-null    int64
 7   max           366 non-null    int64
 8   critical      365 non-null    object
 9   categori      366 non-null    object
 10  lokasi_spku   366 non-null    object
dtypes: int64(5), object(6)
memory usage: 31.6+ KB

In [23]:
ISPU15 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2021-komponen-data.csv')
ISPU15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1825 non-null   int64
 1   tanggal       1825 non-null   object
 2   stasiun       1825 non-null   object
 3   pm10          1825 non-null   object
 4   pm25          1763 non-null   object
 5   so2           1825 non-null   object
 6   co            1825 non-null   object
 7   o3            1825 non-null   object
 8   no2           1825 non-null   object
 9   max           1825 non-null   object
 10  critical      1809 non-null   object
 11  categori      1824 non-null   object
dtypes: int64(1), object(11)
memory usage: 171.2+ KB

In [24]:
ISPU16 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/ISPU/indeks-standar-pencemaran-udara-(ispu)-tahun-2022-komponen-data.csv')
ISPU16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   periode_data    365 non-null    int64
 1   tanggal         365 non-null    object
 2   pm_10           365 non-null    int64
 3   pm_duakomalima  365 non-null    int64
 4   so2             365 non-null    int64
 5   co              365 non-null    int64
 6   o3              365 non-null    int64
 7   no2             365 non-null    int64
 8   max             365 non-null    int64
 9   critical        364 non-null    object
 10  categori        365 non-null    object
 11  lokasi_spku     365 non-null    object
dtypes: int64(8), object(4)
memory usage: 34.3+ KB

# Drop NULL

ISPU 1 tahun bulan tanggal dipisah

In [25]:
ISPU1.head()

,periode_data,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202302,2023-02-25,DKI5 Kebon Jeruk Jakarta Barat,35,-,13,12,31,18,35,PM10,BAIK
1,202302,2023-02-26,DKI5 Kebon Jeruk Jakarta Barat,23,-,14,9,32,11,32,O3,BAIK
2,202302,2023-02-27,DKI5 Kebon Jeruk Jakarta Barat,20,-,13,8,33,13,33,O3,BAIK
3,202302,2023-02-28,DKI5 Kebon Jeruk Jakarta Barat,30,-,21,11,28,18,30,PM10,BAIK
4,202303,2023-03-01,DKI1 Bunderan HI,38,44,50,8,19,27,50,3,BAIK

In [26]:
ISPU1_not_null = ISPU1.rename(columns={'pm_sepuluh': 'pm10',
                              'pm_duakomalima':'pm25',
                              'sulfur_dioksida': 'so2',
                              'karbon_monoksida': 'co',
                              'ozon': 'o3',
                              'nitrogen_dioksida': 'no2',
                              'parameter_pencemar_kritis':'critical'}
                              )
ISPU1_not_null.head()

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,kategori
0,202302,2023-02-25,DKI5 Kebon Jeruk Jakarta Barat,35,-,13,12,31,18,35,PM10,BAIK
1,202302,2023-02-26,DKI5 Kebon Jeruk Jakarta Barat,23,-,14,9,32,11,32,O3,BAIK
2,202302,2023-02-27,DKI5 Kebon Jeruk Jakarta Barat,20,-,13,8,33,13,33,O3,BAIK
3,202302,2023-02-28,DKI5 Kebon Jeruk Jakarta Barat,30,-,21,11,28,18,30,PM10,BAIK
4,202303,2023-03-01,DKI1 Bunderan HI,38,44,50,8,19,27,50,3,BAIK

In [27]:
ISPU1_not_null= ISPU1_not_null.replace('-',np.nan)
ISPU1_not_null.isnull().sum()

periode_data      0
tanggal           0
stasiun           0
pm10            222
pm25            295
so2              39
co               43
o3               28
no2              66
max               3
critical         21
kategori          0
dtype: int64

In [28]:
ISPU1_not_null = ISPU1_not_null.dropna(subset=kolom_penting)

In [29]:
ISPU1_not_null.isnull().sum()

periode_data      0
tanggal           0
stasiun           0
pm10              0
pm25            250
so2               0
co                0
o3                0
no2               0
max               0
critical          0
kategori          0
dtype: int64

ISPU 2 tahun bulan tanggal dipisah(tahun masuh periode_data)

In [30]:
ISPU2.head()

,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202401,1,21,DKI3 Jagakarsa,51.0,65.0,45.0,9.0,8.0,79.0,79.0,NaN,SEDANG
1,202401,1,22,DKI3 Jagakarsa,27.0,34.0,45.0,5.0,8.0,56.0,56.0,NaN,SEDANG
2,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0,PM25,SEDANG
3,202401,1,24,DKI3 Jagakarsa,46.0,65.0,46.0,8.0,9.0,38.0,65.0,PM25,SEDANG
4,202401,1,25,DKI3 Jagakarsa,37.0,55.0,47.0,7.0,11.0,28.0,55.0,PM25,SEDANG

In [31]:
ISPU2_not_null = ISPU2.rename(columns={'pm_sepuluh': 'pm10',
                              'pm_duakomalima':'pm25',
                              'sulfur_dioksida': 'so2',
                              'karbon_monoksida': 'co',
                              'ozon': 'o3',
                              'nitrogen_dioksida': 'no2',
                              'parameter_pencemar_kritis':'critical'}
                              )
ISPU2_not_null.head()

,periode_data,bulan,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,kategori
0,202401,1,21,DKI3 Jagakarsa,51.0,65.0,45.0,9.0,8.0,79.0,79.0,NaN,SEDANG
1,202401,1,22,DKI3 Jagakarsa,27.0,34.0,45.0,5.0,8.0,56.0,56.0,NaN,SEDANG
2,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0,PM25,SEDANG
3,202401,1,24,DKI3 Jagakarsa,46.0,65.0,46.0,8.0,9.0,38.0,65.0,PM25,SEDANG
4,202401,1,25,DKI3 Jagakarsa,37.0,55.0,47.0,7.0,11.0,28.0,55.0,PM25,SEDANG

In [32]:
ISPU2_not_null = ISPU2_not_null.replace('-', np.nan)
ISPU2_not_null.isnull().sum()

periode_data      0
bulan             0
tanggal           0
stasiun           0
pm10            112
pm25             20
so2               9
co               12
o3                9
no2              26
max               5
critical         46
kategori          0
dtype: int64

In [33]:
ISPU2_not_null = ISPU2_not_null.dropna(subset=kolom_penting)
ISPU2_not_null.isnull().sum()

periode_data     0
bulan            0
tanggal          0
stasiun          0
pm10             0
pm25             7
so2              0
co               0
o3               0
no2              0
max              0
critical        39
kategori         0
dtype: int64

sama ISPU2

In [34]:
ISPU3.head()

,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202504,4,24,DKI5 Kebon Jeruk,16.0,50.0,18.0,3.0,16.0,4.0,50.0,PM25,BAIK
1,202504,4,25,DKI5 Kebon Jeruk,23.0,81.0,19.0,9.0,24.0,3.0,81.0,PM25,SEDANG
2,202504,4,26,DKI5 Kebon Jeruk,30.0,77.0,20.0,11.0,29.0,3.0,77.0,PM25,SEDANG
3,202504,4,27,DKI5 Kebon Jeruk,31.0,85.0,21.0,12.0,47.0,4.0,85.0,PM25,SEDANG
4,202504,4,28,DKI5 Kebon Jeruk,24.0,78.0,20.0,9.0,37.0,4.0,78.0,PM25,SEDANG

In [35]:
ISPU3_not_null = ISPU3.rename(columns={'pm_sepuluh': 'pm10',
                              'pm_duakomalima':'pm25',
                              'sulfur_dioksida': 'so2',
                              'karbon_monoksida': 'co',
                              'ozon': 'o3',
                              'nitrogen_dioksida': 'no2',
                              'parameter_pencemar_kritis':'critical'}
                              )
ISPU3_not_null.head()

,periode_data,bulan,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,kategori
0,202504,4,24,DKI5 Kebon Jeruk,16.0,50.0,18.0,3.0,16.0,4.0,50.0,PM25,BAIK
1,202504,4,25,DKI5 Kebon Jeruk,23.0,81.0,19.0,9.0,24.0,3.0,81.0,PM25,SEDANG
2,202504,4,26,DKI5 Kebon Jeruk,30.0,77.0,20.0,11.0,29.0,3.0,77.0,PM25,SEDANG
3,202504,4,27,DKI5 Kebon Jeruk,31.0,85.0,21.0,12.0,47.0,4.0,85.0,PM25,SEDANG
4,202504,4,28,DKI5 Kebon Jeruk,24.0,78.0,20.0,9.0,37.0,4.0,78.0,PM25,SEDANG

In [36]:
ISPU3_not_null = ISPU3_not_null.replace('-', np.nan)
ISPU3_not_null.isnull().sum()

periode_data     0
bulan            0
tanggal          0
stasiun          0
pm10            74
pm25            33
so2             44
co              32
o3              34
no2             40
max              2
critical        16
kategori         0
dtype: int64

In [37]:
ISPU3_not_null = ISPU3_not_null.dropna(subset=kolom_penting)
ISPU3_not_null.isnull().sum()

periode_data     0
bulan            0
tanggal          0
stasiun          0
pm10             0
pm25            15
so2              0
co               0
o3               0
no2              0
max              0
critical         3
kategori         0
dtype: int64

In [38]:
ISPU4

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,201001,2010-01-19,DKI2 (Kelapa Gading),---,---,---,---,---,0,NaN,TIDAK ADA DATA
1,201001,2010-01-20,DKI2 (Kelapa Gading),---,---,---,---,---,0,NaN,TIDAK ADA DATA
2,201001,2010-01-21,DKI2 (Kelapa Gading),---,---,---,---,---,0,NaN,TIDAK ADA DATA
3,201001,2010-01-22,DKI2 (Kelapa Gading),---,---,---,---,---,0,NaN,TIDAK ADA DATA
4,201001,2010-01-23,DKI2 (Kelapa Gading),---,---,---,---,---,0,NaN,TIDAK ADA DATA
...,...,...,...,...,...,...,...,...,...,...,...
1820,201012,2010-12-27,DKI5 (Kebon Jeruk),---,---,---,---,---,0,NaN,TIDAK ADA DATA
1821,201012,2010-12-28,DKI5 (Kebon Jeruk),---,---,---,---,---,0,NaN,TIDAK ADA DATA
1822,201012,2010-12-29,DKI5 (Kebon Jeruk),---,---,---,---,---,0,NaN,TIDAK ADA DATA
1823,201012,2010-12-30,DKI5 (Kebon Jeruk),---,---,---,---,---,0,NaN,TIDAK ADA DATA
1824,201012,2010-12-31,DKI5 (Kebon Jeruk),---,---,---,---,---,0,NaN,TIDAK ADA DATA

In [39]:
ISPU4 = ISPU4.replace('---', np.nan)
ISPU4.head()

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,201001,2010-01-19,DKI2 (Kelapa Gading),NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA
1,201001,2010-01-20,DKI2 (Kelapa Gading),NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA
2,201001,2010-01-21,DKI2 (Kelapa Gading),NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA
3,201001,2010-01-22,DKI2 (Kelapa Gading),NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA
4,201001,2010-01-23,DKI2 (Kelapa Gading),NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA

In [40]:
kolom_penting = [
    'pm10',
    'so2',
    'co',
    'o3',
    'no2'
]

ISPU4_not_null = ISPU4.dropna(subset=kolom_penting)

ISPU4_not_null.head()

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
47,201002,2010-02-02,DKI1 (Bunderan HI),50,4,30,23,12,50,PM10,BAIK
48,201002,2010-02-03,DKI1 (Bunderan HI),49,7,33,57,23,57,O3,SEDANG
49,201002,2010-02-04,DKI1 (Bunderan HI),59,9,38,75,26,75,O3,SEDANG
50,201002,2010-02-05,DKI1 (Bunderan HI),63,7,39,41,23,63,PM10,SEDANG
51,201002,2010-02-06,DKI1 (Bunderan HI),65,8,59,24,15,65,PM10,SEDANG

In [41]:
ISPU4_not_null.shape

(467, 11)

In [42]:
ISPU5.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201105,2011-05-01,71,18,54,88,31,88,O3,SEDANG,DKI1
1,201105,2011-05-02,61,19,35,98,29,98,O3,SEDANG,DKI4
2,201105,2011-05-03,69,22,31,69,28,69,PM10,SEDANG,DKI1
3,201105,2011-05-04,63,18,26,47,17,63,PM10,SEDANG,DKI4
4,201105,2011-05-05,76,17,28,63,20,76,PM10,SEDANG,DKI4

In [43]:
ISPU5.shape

(365, 11)

In [44]:
ISPU5 = ISPU5.replace('---', np.nan)

In [45]:
ISPU5 = ISPU5.replace('---', np.nan)
ISPU5_not_null = ISPU5.dropna(subset=kolom_penting)
ISPU5_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201105,2011-05-01,71,18,54,88,31,88,O3,SEDANG,DKI1
1,201105,2011-05-02,61,19,35,98,29,98,O3,SEDANG,DKI4
2,201105,2011-05-03,69,22,31,69,28,69,PM10,SEDANG,DKI1
3,201105,2011-05-04,63,18,26,47,17,63,PM10,SEDANG,DKI4
4,201105,2011-05-05,76,17,28,63,20,76,PM10,SEDANG,DKI4
...,...,...,...,...,...,...,...,...,...,...,...
360,201111,2011-11-26,79,19,33,126,15,126,O3,TIDAK SEHAT,DKI2
361,201111,2011-11-27,74,12,23,133,13,133,O3,TIDAK SEHAT,DKI2
362,201111,2011-11-28,134,27,35,159,26,159,O3,TIDAK SEHAT,DKI2
363,201111,2011-11-29,91,23,32,104,19,104,O3,TIDAK SEHAT,DKI2
364,201111,2011-11-30,75,20,28,164,20,164,O3,TIDAK SEHAT,DKI2

In [46]:
ISPU6.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201201,2012-01-01,52,18,39,63,7,63,O3,SEDANG,DKI2
1,201201,2012-01-02,49,22,28,55,11,55,O3,SEDANG,DKI2
2,201201,2012-01-03,65,15,42,86,22,86,O3,SEDANG,DKI1
3,201201,2012-01-04,69,20,55,97,20,97,O3,SEDANG,DKI1
4,201201,2012-01-05,67,14,39,157,25,157,O3,TIDAK SEHAT,DKI2

In [47]:
ISPU6 = ISPU6.replace('---', np.nan)
ISPU6_not_null = ISPU6.dropna(subset=kolom_penting)
ISPU6_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201201,2012-01-01,52,18,39,63,7,63,O3,SEDANG,DKI2
1,201201,2012-01-02,49,22,28,55,11,55,O3,SEDANG,DKI2
2,201201,2012-01-03,65,15,42,86,22,86,O3,SEDANG,DKI1
3,201201,2012-01-04,69,20,55,97,20,97,O3,SEDANG,DKI1
4,201201,2012-01-05,67,14,39,157,25,157,O3,TIDAK SEHAT,DKI2
...,...,...,...,...,...,...,...,...,...,...,...
361,201211,2012-11-26,58,34,40,203,18,203,O3,SANGAT TIDAK SEHAT,DKI2
362,201211,2012-11-27,84,37,52,215,18,215,O3,SANGAT TIDAK SEHAT,DKI2
363,201211,2012-11-28,62,30,47,227,16,227,O3,SANGAT TIDAK SEHAT,DKI2
364,201211,2012-11-29,69,32,49,218,22,218,O3,SANGAT TIDAK SEHAT,DKI2
365,201211,2012-11-30,76,30,76,137,22,137,O3,TIDAK SEHAT,DKI2

In [48]:
ISPU7.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201301,2013-01-01,75,4,27,135,10,135,O3,TIDAK SEHAT,DKI2
1,201301,2013-01-02,35,4,26,192,8,192,O3,TIDAK SEHAT,DKI2
2,201301,2013-01-03,61,5,36,195,9,195,O3,TIDAK SEHAT,DKI2
3,201301,2013-01-04,39,4,13,210,10,210,O3,SANGAT TIDAK SEHAT,DKI2
4,201301,2013-01-05,53,5,14,111,8,111,O3,TIDAK SEHAT,DKI2

In [49]:
ISPU7.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
categori        0
lokasi_spku     0
dtype: int64

In [50]:
ISPU7.shape

(365, 11)

In [51]:
ISPU7 = ISPU7.replace('---', np.nan)
ISPU7_not_null = ISPU7.dropna(subset=kolom_penting)
ISPU7_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201301,2013-01-01,75,4,27,135,10,135,O3,TIDAK SEHAT,DKI2
1,201301,2013-01-02,35,4,26,192,8,192,O3,TIDAK SEHAT,DKI2
2,201301,2013-01-03,61,5,36,195,9,195,O3,TIDAK SEHAT,DKI2
3,201301,2013-01-04,39,4,13,210,10,210,O3,SANGAT TIDAK SEHAT,DKI2
4,201301,2013-01-05,53,5,14,111,8,111,O3,TIDAK SEHAT,DKI2
...,...,...,...,...,...,...,...,...,...,...,...
360,201312,2013-12-27,72,10,61,71,17,72,PM10,SEDANG,DKI4
361,201312,2013-12-28,67,7,50,65,11,67,PM10,SEDANG,DKI4
362,201312,2013-12-29,53,8,21,63,12,63,O3,SEDANG,DKI4
363,201312,2013-12-30,41,10,26,67,12,67,O3,SEDANG,DKI4
364,201312,2013-12-31,28,6,26,69,13,69,O3,SEDANG,DKI4

In [52]:
ISPU8.head()

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,201401,2014-01-01,DKI1 (Bunderan HI),77,3,39,54,13,77,PM10,SEDANG
1,201401,2014-01-02,DKI1 (Bunderan HI),55,4,29,58,12,58,O3,SEDANG
2,201401,2014-01-03,DKI1 (Bunderan HI),60,5,40,68,13,68,O3,SEDANG
3,201401,2014-01-04,DKI1 (Bunderan HI),55,7,30,56,14,56,O3,SEDANG
4,201401,2014-01-05,DKI1 (Bunderan HI),39,4,18,48,10,48,O3,BAIK

In [53]:
ISPU8.isnull().sum()

periode_data     0
tanggal          0
stasiun          0
pm10             0
so2              0
co               0
o3               0
no2              0
max              0
critical        34
categori         0
dtype: int64

In [54]:
ISPU8.shape

(1825, 11)

In [55]:
ISPU8 = ISPU8.replace('---', np.nan)
ISPU8_not_null = ISPU8.dropna(subset=kolom_penting)
ISPU8_not_null

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,201401,2014-01-01,DKI1 (Bunderan HI),77,3,39,54,13,77,PM10,SEDANG
1,201401,2014-01-02,DKI1 (Bunderan HI),55,4,29,58,12,58,O3,SEDANG
2,201401,2014-01-03,DKI1 (Bunderan HI),60,5,40,68,13,68,O3,SEDANG
3,201401,2014-01-04,DKI1 (Bunderan HI),55,7,30,56,14,56,O3,SEDANG
4,201401,2014-01-05,DKI1 (Bunderan HI),39,4,18,48,10,48,O3,BAIK
...,...,...,...,...,...,...,...,...,...,...,...
1820,201412,2014-12-27,DKI5 (Kebon Jeruk),16,3,10,3,8,16,PM10,BAIK
1821,201412,2014-12-28,DKI5 (Kebon Jeruk),19,3,24,3,9,24,CO,BAIK
1822,201412,2014-12-29,DKI5 (Kebon Jeruk),11,3,8,3,3,11,PM10,BAIK
1823,201412,2014-12-30,DKI5 (Kebon Jeruk),18,3,8,3,4,18,PM10,BAIK
1824,201412,2014-12-31,DKI5 (Kebon Jeruk),14,3,5,3,2,14,PM10,BAIK

In [56]:
ISPU9.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201505,2015-05-19,84,18,31,105,19,105,O3,TIDAK SEHAT,DKI3
1,201505,2015-05-20,83,18,30,97,22,97,O3,SEDANG,DKI3
2,201505,2015-05-21,87,18,32,84,19,87,PM10,SEDANG,DKI4
3,201505,2015-05-22,85,19,27,90,17,90,O3,SEDANG,DKI5
4,201505,2015-05-23,93,22,36,90,18,93,PM10,SEDANG,DKI4

In [57]:
ISPU9.shape

(365, 11)

In [58]:
ISPU9 = ISPU9.replace('---', np.nan)

In [59]:
ISPU9.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
categori        0
lokasi_spku     0
dtype: int64

In [60]:
ISPU9_not_null = ISPU9.dropna(subset=kolom_penting)
ISPU9_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201505,2015-05-19,84,18,31,105,19,105,O3,TIDAK SEHAT,DKI3
1,201505,2015-05-20,83,18,30,97,22,97,O3,SEDANG,DKI3
2,201505,2015-05-21,87,18,32,84,19,87,PM10,SEDANG,DKI4
3,201505,2015-05-22,85,19,27,90,17,90,O3,SEDANG,DKI5
4,201505,2015-05-23,93,22,36,90,18,93,PM10,SEDANG,DKI4
...,...,...,...,...,...,...,...,...,...,...,...
360,201509,2015-09-26,77,34,28,68,18,77,PM10,SEDANG,DKI1
361,201509,2015-09-27,80,32,22,78,13,80,PM10,SEDANG,DKI4
362,201509,2015-09-28,76,30,25,94,19,94,O3,SEDANG,DKI3
363,201509,2015-09-29,105,31,30,69,20,105,PM10,TIDAK SEHAT,DKI4
364,201509,2015-09-30,92,33,25,67,23,92,PM10,SEDANG,DKI4

In [61]:
ISPU10.head()

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,201602,2016-02-12,DKI2 (Kelapa Gading),41,3,24,35,15,41,PM10,BAIK
1,201602,2016-02-13,DKI2 (Kelapa Gading),73,16,47,72,23,73,PM10,SEDANG
2,201602,2016-02-14,DKI2 (Kelapa Gading),62,21,24,86,15,86,O3,SEDANG
3,201602,2016-02-15,DKI2 (Kelapa Gading),55,9,29,63,12,63,O3,SEDANG
4,201602,2016-02-16,DKI2 (Kelapa Gading),50,6,22,31,14,50,PM10,BAIK

In [62]:
ISPU10.isnull().sum()

periode_data     0
tanggal          0
stasiun          0
pm10             0
so2              0
co               0
o3               0
no2              0
max              0
critical        37
categori         0
dtype: int64

In [63]:
ISPU10_not_null = ISPU10.replace('---', np.nan)

In [64]:
ISPU10_not_null.isnull().sum()

periode_data      0
tanggal           0
stasiun           0
pm10            128
so2              75
co               88
o3              107
no2             117
max               0
critical         37
categori          0
dtype: int64

In [65]:
ISPU10_not_null = ISPU10_not_null.dropna(subset=kolom_penting)
ISPU10_not_null.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
categori        0
dtype: int64

In [66]:
ISPU11.head()

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,201701,2017-01-27,DKI5 (Kebon Jeruk),5,11,29,37,14,37,O3,BAIK
1,201701,2017-01-28,DKI5 (Kebon Jeruk),5,11,28,42,6,42,O3,BAIK
2,201701,2017-01-29,DKI5 (Kebon Jeruk),6,11,29,26,13,29,CO,BAIK
3,201701,2017-01-30,DKI5 (Kebon Jeruk),7,11,28,41,5,41,O3,BAIK
4,201701,2017-01-31,DKI5 (Kebon Jeruk),6,11,26,42,7,42,O3,BAIK

In [67]:
ISPU11_not_null = ISPU11.replace('---', np.nan)
ISPU11_not_null.isnull().sum()

periode_data      0
tanggal           0
stasiun           0
pm10            115
so2              79
co               95
o3               87
no2              86
max               5
critical         30
categori          0
dtype: int64

In [68]:
ISPU11_not_null = ISPU11_not_null.dropna(subset=kolom_penting)
ISPU11_not_null.isnull().isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
categori        0
dtype: int64

In [69]:
ISPU12.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201804,01/04/2018,45,25,17,57,13,57,O3,SEDANG,DKI5
1,201804,02/04/2018,46,27,18,57,19,57,O3,SEDANG,DKI5
2,201804,03/04/2018,50,26,27,80,26,80,O3,SEDANG,DKI5
3,201804,04/04/2018,45,28,20,96,28,96,O3,SEDANG,DKI5
4,201804,05/04/2018,81,37,29,202,18,202,O3,SANGAT TIDAK SEHAT,DKI5

In [70]:
ISPU12_not_null = ISPU12.replace('---',np.nan)

In [71]:
ISPU11_not_null.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
categori        0
dtype: int64

In [72]:
ISPU12.shape

(365, 11)

In [73]:
ISPU13.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201903,2019-03-01,58,19,29,70,15,70,O3,SEDANG,DKI3
1,201903,2019-03-02,50,51,25,62,12,62,O3,SEDANG,DKI3
2,201903,2019-03-03,53,23,22,82,15,82,O3,SEDANG,DKI5
3,201903,2019-03-04,55,22,32,104,22,104,O3,TIDAK SEHAT,DKI3
4,201903,2019-03-05,47,21,28,83,22,83,O3,SEDANG,DKI5

In [74]:
ISPU13_not_null = ISPU13.replace('---', np.nan)
ISPU13_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
categori        0
lokasi_spku     0
dtype: int64

In [75]:
ISPU13.shape

(345, 11)

In [76]:
ISPU14.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,202005,2020-05-01,55,26,21,83,10,83,O3,SEDANG,DKI5
1,202005,2020-05-02,36,22,12,80,9,80,O3,SEDANG,DKI5
2,202005,2020-05-03,65,34,35,49,11,65,PM10,SEDANG,DKI5
3,202005,2020-05-04,53,21,14,75,8,75,O3,SEDANG,DKI5
4,202005,2020-05-05,53,22,18,73,9,73,O3,SEDANG,DKI5

In [77]:
ISPU14_not_null = ISPU14.replace('---', np.nan)
ISPU14_not_null.isnull().sum()

periode_data     0
tanggal          0
pm10             0
so2             13
co               1
o3               0
no2              0
max              0
critical         1
categori         0
lokasi_spku      0
dtype: int64

In [78]:
ISPU14_not_null = ISPU14_not_null.dropna(subset=kolom_penting)
ISPU14_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        1
categori        0
lokasi_spku     0
dtype: int64

ISPU15 masih ada pm25

In [79]:
ISPU15.head()

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,202101,2021-01-22,DKI5 (Kebon Jeruk) Jakarta Barat,45,NaN,21,13,40,15,45,PM10,BAIK
1,202101,2021-01-23,DKI5 (Kebon Jeruk) Jakarta Barat,80,NaN,22,44,44,22,80,PM10,SEDANG
2,202101,2021-01-24,DKI5 (Kebon Jeruk) Jakarta Barat,27,NaN,14,9,29,---,29,CO,BAIK
3,202101,2021-01-25,DKI5 (Kebon Jeruk) Jakarta Barat,55,NaN,19,29,67,13,67,CO,SEDANG
4,202101,2021-01-26,DKI5 (Kebon Jeruk) Jakarta Barat,57,NaN,21,23,36,16,57,PM10,SEDANG

In [80]:
ISPU15_not_null = ISPU15.replace('---', np.nan)
ISPU15_not_null.isnull().sum()

periode_data      0
tanggal           0
stasiun           0
pm10             68
pm25            100
so2             114
co               36
o3               68
no2              35
max               0
critical         16
categori          1
dtype: int64

In [81]:
ISPU15_not_null = ISPU15_not_null.dropna(subset=kolom_penting)
ISPU15_not_null.isnull().sum()

periode_data     0
tanggal          0
stasiun          0
pm10             0
pm25            68
so2              0
co               0
o3               0
no2              0
max              0
critical         0
categori         1
dtype: int64

In [82]:
ISPU15_not_null

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,202101,2021-01-22,DKI5 (Kebon Jeruk) Jakarta Barat,45,NaN,21,13,40,15,45,PM10,BAIK
1,202101,2021-01-23,DKI5 (Kebon Jeruk) Jakarta Barat,80,NaN,22,44,44,22,80,PM10,SEDANG
3,202101,2021-01-25,DKI5 (Kebon Jeruk) Jakarta Barat,55,NaN,19,29,67,13,67,CO,SEDANG
4,202101,2021-01-26,DKI5 (Kebon Jeruk) Jakarta Barat,57,NaN,21,23,36,16,57,PM10,SEDANG
7,202101,2021-01-29,DKI5 (Kebon Jeruk) Jakarta Barat,30,NaN,22,10,32,11,32,CO,BAIK
...,...,...,...,...,...,...,...,...,...,...,...,...
1820,202112,2021-12-30,DKI2 (Kelapa Gading),47,64,38,13,38,35,64,PM25,SEDANG
1821,202112,2021-12-31,DKI2 (Kelapa Gading),61,85,33,23,37,44,85,PM25,SEDANG
1822,202112,2021-12-01,DKI3 (Jagakarsa),53,70,43,12,32,15,70,PM25,SEDANG
1823,202112,2021-12-02,DKI3 (Jagakarsa),35,55,42,7,29,9,55,PM25,SEDANG
1824,202112,2021-12-03,DKI3 (Jagakarsa),54,67,43,9,32,11,67,PM25,SEDANG

ISPU16 ada pm 2.5

In [83]:
ISPU16.head()

,periode_data,tanggal,pm_10,pm_duakomalima,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,202212,44926.625,54,73,56,24,23,24,73,"PM2,5",SEDANG,DKI4
1,202212,2022-12-30,40,64,57,21,17,24,64,"PM2,5",SEDANG,DKI4
2,202207,2022-07-06,75,129,45,25,71,26,129,"PM2,5",TIDAK SEHAT,DKI4
3,202207,2022-07-05,66,110,47,16,61,23,110,"PM2,5",TIDAK SEHAT,DKI4
4,202207,2022-07-04,56,78,49,11,60,13,78,"PM2,5",SEDANG,DKI4

In [84]:
ISPU16_not_null = ISPU16.replace('---', np.nan)

In [85]:
ISPU16_not_null.isnull().sum()

periode_data      0
tanggal           0
pm_10             0
pm_duakomalima    0
so2               0
co                0
o3                0
no2               0
max               0
critical          1
categori          0
lokasi_spku       0
dtype: int64

# Samakan Tanggal

In [86]:
# tanggal
ISPU1_not_null['tanggal'] = pd.to_datetime(ISPU1_not_null['tanggal'], errors='coerce')

In [87]:
ISPU2_not_null['tanggal'] = pd.to_datetime(
    {
        'year': 2024,
        'month': ISPU2_not_null['bulan'],
        'day': ISPU2_not_null['tanggal']
    }
)

In [88]:
ISPU2_not_null.drop(columns=['bulan'], inplace=True)

In [89]:
ISPU2_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1687 entries, 0 to 1798
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1687 non-null   int64
 1   tanggal       1687 non-null   datetime64[ns]
 2   stasiun       1687 non-null   object
 3   pm10          1687 non-null   float64
 4   pm25          1680 non-null   float64
 5   so2           1687 non-null   float64
 6   co            1687 non-null   float64
 7   o3            1687 non-null   float64
 8   no2           1687 non-null   float64
 9   max           1687 non-null   float64
 10  critical      1648 non-null   object
 11  kategori      1687 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 171.3+ KB

In [90]:
ISPU3_not_null

,periode_data,bulan,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,kategori
0,202504,4,24,DKI5 Kebon Jeruk,16.0,50.0,18.0,3.0,16.0,4.0,50.0,PM25,BAIK
1,202504,4,25,DKI5 Kebon Jeruk,23.0,81.0,19.0,9.0,24.0,3.0,81.0,PM25,SEDANG
2,202504,4,26,DKI5 Kebon Jeruk,30.0,77.0,20.0,11.0,29.0,3.0,77.0,PM25,SEDANG
3,202504,4,27,DKI5 Kebon Jeruk,31.0,85.0,21.0,12.0,47.0,4.0,85.0,PM25,SEDANG
4,202504,4,28,DKI5 Kebon Jeruk,24.0,78.0,20.0,9.0,37.0,4.0,78.0,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,202508,8,30,DKI3 Jagakarsa,21.0,59.0,53.0,8.0,23.0,46.0,59.0,PM25,SEDANG
1210,202508,8,31,DKI3 Jagakarsa,28.0,60.0,53.0,8.0,19.0,39.0,60.0,PM25,SEDANG
1211,202508,8,1,DKI4 Lubang Buaya,63.0,89.0,30.0,7.0,28.0,16.0,89.0,PM25,SEDANG
1212,202508,8,2,DKI4 Lubang Buaya,73.0,105.0,31.0,11.0,25.0,21.0,105.0,PM25,TIDAK SEHAT
1214,202508,8,4,DKI4 Lubang Buaya,63.0,84.0,27.0,14.0,26.0,26.0,84.0,PM25,SEDANG

In [91]:
ISPU3_not_null['tanggal'] = pd.to_datetime(
    {
        'year': 2025,
        'month': ISPU3_not_null['bulan'],
        'day': ISPU3_not_null['tanggal']
    }
)

In [92]:
ISPU3_not_null.drop(columns=['bulan'], inplace=True)

In [93]:
ISPU3_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1096 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1096 non-null   int64
 1   tanggal       1096 non-null   datetime64[ns]
 2   stasiun       1096 non-null   object
 3   pm10          1096 non-null   float64
 4   pm25          1081 non-null   float64
 5   so2           1096 non-null   float64
 6   co            1096 non-null   float64
 7   o3            1096 non-null   float64
 8   no2           1096 non-null   float64
 9   max           1096 non-null   float64
 10  critical      1093 non-null   object
 11  kategori      1096 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 111.3+ KB

In [94]:
# tanggal
ISPU4_not_null['tanggal'] = pd.to_datetime(ISPU4_not_null['tanggal'], errors='coerce')

/tmp/ipython-input-1343887346.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ISPU4_not_null['tanggal'] = pd.to_datetime(ISPU4_not_null['tanggal'], errors='coerce')

In [95]:
ISPU4_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 467 entries, 47 to 1786
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  467 non-null    int64
 1   tanggal       467 non-null    datetime64[ns]
 2   stasiun       467 non-null    object
 3   pm10          467 non-null    object
 4   so2           467 non-null    object
 5   co            467 non-null    object
 6   o3            467 non-null    object
 7   no2           467 non-null    object
 8   max           467 non-null    int64
 9   critical      467 non-null    object
 10  categori      467 non-null    object
dtypes: datetime64[ns](1), int64(2), object(8)
memory usage: 59.9+ KB

In [96]:
# tanggal
ISPU5_not_null['tanggal'] = pd.to_datetime(ISPU5_not_null['tanggal'], errors='coerce')

In [97]:
# tanggal
ISPU6_not_null['tanggal'] = pd.to_datetime(ISPU6_not_null['tanggal'], errors='coerce')

In [98]:
# tanggal
ISPU7_not_null['tanggal'] = pd.to_datetime(ISPU7_not_null['tanggal'], errors='coerce')

In [99]:
# tanggal
ISPU8_not_null['tanggal'] = pd.to_datetime(ISPU8_not_null['tanggal'], errors='coerce')

/tmp/ipython-input-672994599.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ISPU8_not_null['tanggal'] = pd.to_datetime(ISPU8_not_null['tanggal'], errors='coerce')

In [100]:
# tanggal
ISPU9_not_null['tanggal'] = pd.to_datetime(ISPU9_not_null['tanggal'], errors='coerce')

In [101]:
# tanggal
ISPU10_not_null['tanggal'] = pd.to_datetime(ISPU10_not_null['tanggal'], errors='coerce')

In [102]:
# tanggal
ISPU11_not_null['tanggal'] = pd.to_datetime(ISPU11_not_null['tanggal'], errors='coerce')

In [103]:
# tanggal
ISPU12_not_null['tanggal'] = pd.to_datetime(ISPU12_not_null['tanggal'], errors='coerce')

In [104]:
# tanggal
ISPU13_not_null['tanggal'] = pd.to_datetime(ISPU13_not_null['tanggal'], errors='coerce')

In [105]:
# tanggal
ISPU14_not_null['tanggal'] = pd.to_datetime(ISPU14_not_null['tanggal'], errors='coerce')

In [106]:
# tanggal
ISPU15_not_null['tanggal'] = pd.to_datetime(ISPU15_not_null['tanggal'], errors='coerce')

In [107]:
# tanggal
ISPU16_not_null['tanggal'] = pd.to_datetime(ISPU16_not_null['tanggal'], errors='coerce')

/tmp/ipython-input-2138671525.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ISPU16_not_null['tanggal'] = pd.to_datetime(ISPU16_not_null['tanggal'], errors='coerce')

In [108]:
ISPU16_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   periode_data    365 non-null    int64
 1   tanggal         364 non-null    datetime64[ns]
 2   pm_10           365 non-null    int64
 3   pm_duakomalima  365 non-null    int64
 4   so2             365 non-null    int64
 5   co              365 non-null    int64
 6   o3              365 non-null    int64
 7   no2             365 non-null    int64
 8   max             365 non-null    int64
 9   critical        364 non-null    object
 10  categori        365 non-null    object
 11  lokasi_spku     365 non-null    object
dtypes: datetime64[ns](1), int64(8), object(3)
memory usage: 34.3+ KB

# Samakan Tipe Data

In [109]:
kolom_numerik_pm25 = [c for c in kolom_numerik_pm25 if c in ISPU1_not_null.columns]

ISPU1_not_null[kolom_numerik_pm25] = (
    ISPU1_not_null[kolom_numerik_pm25]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [110]:
ISPU1_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1536 entries, 0 to 1824
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1536 non-null   int64
 1   tanggal       1536 non-null   datetime64[ns]
 2   stasiun       1536 non-null   object
 3   pm10          1536 non-null   float64
 4   pm25          1286 non-null   float64
 5   so2           1536 non-null   float64
 6   co            1535 non-null   float64
 7   o3            1535 non-null   float64
 8   no2           1536 non-null   float64
 9   max           1536 non-null   float64
 10  critical      1536 non-null   object
 11  kategori      1536 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 156.0+ KB

In [111]:
kolom_numerik_pm25 = [c for c in kolom_numerik_pm25 if c in ISPU2_not_null.columns]

ISPU2_not_null[kolom_numerik_pm25] = (
    ISPU2_not_null[kolom_numerik_pm25]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [112]:
kolom_numerik_pm25 = [c for c in kolom_numerik_pm25 if c in ISPU3_not_null.columns]

ISPU3_not_null[kolom_numerik_pm25] = (
    ISPU3_not_null[kolom_numerik_pm25]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [113]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU4_not_null.columns]

ISPU4_not_null[kolom_numerik] = (
    ISPU4_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

/tmp/ipython-input-1362876964.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ISPU4_not_null[kolom_numerik] = (

In [114]:
ISPU4_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 467 entries, 47 to 1786
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  467 non-null    int64
 1   tanggal       467 non-null    datetime64[ns]
 2   stasiun       467 non-null    object
 3   pm10          467 non-null    float64
 4   so2           467 non-null    float64
 5   co            467 non-null    float64
 6   o3            467 non-null    float64
 7   no2           467 non-null    float64
 8   max           467 non-null    float64
 9   critical      467 non-null    object
 10  categori      467 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 59.9+ KB

In [115]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU5_not_null.columns]

ISPU5_not_null[kolom_numerik] = (
    ISPU5_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [116]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU6_not_null.columns]

ISPU6_not_null[kolom_numerik] = (
    ISPU6_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [117]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU7_not_null.columns]

ISPU7_not_null[kolom_numerik] = (
    ISPU7_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [118]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU8_not_null.columns]

ISPU8_not_null[kolom_numerik] = (
    ISPU8_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

/tmp/ipython-input-3080424766.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ISPU8_not_null[kolom_numerik] = (

In [119]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU9_not_null.columns]

ISPU9_not_null[kolom_numerik] = (
    ISPU9_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [120]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU10_not_null.columns]

ISPU10_not_null[kolom_numerik] = (
    ISPU10_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [121]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU11_not_null.columns]

ISPU11_not_null[kolom_numerik] = (
    ISPU11_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [122]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU12_not_null.columns]

ISPU12_not_null[kolom_numerik] = (
    ISPU12_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [123]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU13_not_null.columns]

ISPU13_not_null[kolom_numerik] = (
    ISPU13_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [124]:
kolom_numerik = [c for c in kolom_numerik if c in ISPU14_not_null.columns]

ISPU14_not_null[kolom_numerik] = (
    ISPU14_not_null[kolom_numerik]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [125]:
kolom_numerik_pm25 = [c for c in kolom_numerik_pm25 if c in ISPU15_not_null.columns]

ISPU15_not_null[kolom_numerik_pm25] = (
    ISPU15_not_null[kolom_numerik_pm25]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [126]:
ISPU16_not_null.rename(columns={'pm_10': 'pm10'}, inplace=True)
ISPU16_not_null.rename(columns={'pm_duakomalima': 'pm25'}, inplace=True)

In [127]:
kolom_numerik_pm25 = [c for c in kolom_numerik_pm25 if c in ISPU16_not_null.columns]

ISPU16_not_null[kolom_numerik_pm25] = (
    ISPU16_not_null[kolom_numerik_pm25]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [128]:
ISPU16_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       364 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   pm25          365 non-null    float64
 4   so2           365 non-null    float64
 5   co            365 non-null    float64
 6   o3            365 non-null    float64
 7   no2           365 non-null    float64
 8   max           365 non-null    float64
 9   critical      364 non-null    object
 10  categori      365 non-null    object
 11  lokasi_spku   365 non-null    object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 34.3+ KB

In [129]:
ISPU16_not_null['pm10'] = (
    ISPU16_not_null['pm10']
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [130]:
ISPU16_not_null['pm25'] = (
    ISPU16_not_null['pm25']
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

In [131]:
ISPU16_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       364 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   pm25          365 non-null    float64
 4   so2           365 non-null    float64
 5   co            365 non-null    float64
 6   o3            365 non-null    float64
 7   no2           365 non-null    float64
 8   max           365 non-null    float64
 9   critical      364 non-null    object
 10  categori      365 non-null    object
 11  lokasi_spku   365 non-null    object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 34.3+ KB

# Clean category

In [132]:
ISPU1_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1536 entries, 0 to 1824
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1536 non-null   int64
 1   tanggal       1536 non-null   datetime64[ns]
 2   stasiun       1536 non-null   object
 3   pm10          1536 non-null   float64
 4   pm25          1286 non-null   float64
 5   so2           1536 non-null   float64
 6   co            1535 non-null   float64
 7   o3            1535 non-null   float64
 8   no2           1536 non-null   float64
 9   max           1536 non-null   float64
 10  critical      1536 non-null   object
 11  kategori      1536 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 156.0+ KB

In [133]:
kolom_kategori = [c for c in kolom_kategori if c in ISPU1_not_null.columns]

for col in kolom_kategori:
    ISPU1_not_null[col] = (
        ISPU1_not_null[col]
        .astype(str)
        .str.strip()
        .str.upper()
    )

ISPU1_not_null[kolom_kategori] = ISPU1_not_null[kolom_kategori].astype('category')

In [134]:
ISPU2_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1687 entries, 0 to 1798
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1687 non-null   int64
 1   tanggal       1687 non-null   datetime64[ns]
 2   stasiun       1687 non-null   object
 3   pm10          1687 non-null   float64
 4   pm25          1680 non-null   float64
 5   so2           1687 non-null   float64
 6   co            1687 non-null   float64
 7   o3            1687 non-null   float64
 8   no2           1687 non-null   float64
 9   max           1687 non-null   float64
 10  critical      1648 non-null   object
 11  kategori      1687 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 171.3+ KB

In [135]:
ISPU3_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1096 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1096 non-null   int64
 1   tanggal       1096 non-null   datetime64[ns]
 2   stasiun       1096 non-null   object
 3   pm10          1096 non-null   float64
 4   pm25          1081 non-null   float64
 5   so2           1096 non-null   float64
 6   co            1096 non-null   float64
 7   o3            1096 non-null   float64
 8   no2           1096 non-null   float64
 9   max           1096 non-null   float64
 10  critical      1093 non-null   object
 11  kategori      1096 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 111.3+ KB

In [136]:
ISPU4_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 467 entries, 47 to 1786
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  467 non-null    int64
 1   tanggal       467 non-null    datetime64[ns]
 2   stasiun       467 non-null    object
 3   pm10          467 non-null    float64
 4   so2           467 non-null    float64
 5   co            467 non-null    float64
 6   o3            467 non-null    float64
 7   no2           467 non-null    float64
 8   max           467 non-null    float64
 9   critical      467 non-null    object
 10  categori      467 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 59.9+ KB

In [137]:
ISPU4_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

/tmp/ipython-input-3266581128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ISPU4_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [138]:
ISPU5_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   so2           365 non-null    float64
 4   co            365 non-null    float64
 5   o3            365 non-null    float64
 6   no2           365 non-null    float64
 7   max           365 non-null    float64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 31.5+ KB

In [139]:
ISPU5_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU5_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [140]:
ISPU6_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  366 non-null    int64
 1   tanggal       366 non-null    datetime64[ns]
 2   pm10          366 non-null    float64
 3   so2           366 non-null    float64
 4   co            366 non-null    float64
 5   o3            366 non-null    float64
 6   no2           366 non-null    float64
 7   max           366 non-null    float64
 8   critical      366 non-null    object
 9   categori      366 non-null    object
 10  lokasi_spku   366 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 31.6+ KB

In [141]:
ISPU6_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU6_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [142]:
ISPU7_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       335 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   so2           365 non-null    float64
 4   co            365 non-null    float64
 5   o3            365 non-null    float64
 6   no2           365 non-null    float64
 7   max           365 non-null    float64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 31.5+ KB

In [143]:
ISPU7_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU7_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [144]:
ISPU8_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1501 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1501 non-null   int64
 1   tanggal       1501 non-null   datetime64[ns]
 2   stasiun       1501 non-null   object
 3   pm10          1501 non-null   float64
 4   so2           1501 non-null   float64
 5   co            1501 non-null   float64
 6   o3            1501 non-null   float64
 7   no2           1501 non-null   float64
 8   max           1501 non-null   float64
 9   critical      1501 non-null   object
 10  categori      1501 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 173.0+ KB

In [145]:

ISPU8_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

/tmp/ipython-input-2188480879.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ISPU8_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [146]:
ISPU9_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   so2           365 non-null    float64
 4   co            365 non-null    float64
 5   o3            365 non-null    float64
 6   no2           365 non-null    float64
 7   max           365 non-null    float64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 31.5+ KB

In [147]:
ISPU9_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU9_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [148]:
ISPU10_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1546 entries, 0 to 1829
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1546 non-null   int64
 1   tanggal       1484 non-null   datetime64[ns]
 2   stasiun       1546 non-null   object
 3   pm10          1546 non-null   float64
 4   so2           1546 non-null   float64
 5   co            1546 non-null   float64
 6   o3            1546 non-null   float64
 7   no2           1546 non-null   float64
 8   max           1546 non-null   float64
 9   critical      1546 non-null   object
 10  categori      1546 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 144.9+ KB

In [149]:

ISPU10_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [150]:
ISPU11_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1534 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1534 non-null   int64
 1   tanggal       1534 non-null   datetime64[ns]
 2   stasiun       1534 non-null   object
 3   pm10          1534 non-null   float64
 4   so2           1534 non-null   float64
 5   co            1534 non-null   float64
 6   o3            1534 non-null   float64
 7   no2           1534 non-null   float64
 8   max           1534 non-null   float64
 9   critical      1534 non-null   object
 10  categori      1534 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 143.8+ KB

In [151]:

ISPU11_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [152]:
ISPU12_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       144 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   so2           365 non-null    float64
 4   co            365 non-null    float64
 5   o3            365 non-null    float64
 6   no2           365 non-null    float64
 7   max           365 non-null    float64
 8   critical      365 non-null    object
 9   categori      365 non-null    object
 10  lokasi_spku   365 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 31.5+ KB

In [153]:
ISPU12_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU12_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [154]:
ISPU13_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  345 non-null    int64
 1   tanggal       345 non-null    datetime64[ns]
 2   pm10          345 non-null    float64
 3   so2           345 non-null    float64
 4   co            345 non-null    float64
 5   o3            345 non-null    float64
 6   no2           345 non-null    float64
 7   max           345 non-null    float64
 8   critical      345 non-null    object
 9   categori      345 non-null    object
 10  lokasi_spku   345 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 29.8+ KB

In [155]:
ISPU13_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU13_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [156]:
ISPU14_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 353 entries, 0 to 365
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  353 non-null    int64
 1   tanggal       353 non-null    datetime64[ns]
 2   pm10          353 non-null    float64
 3   so2           353 non-null    float64
 4   co            353 non-null    float64
 5   o3            353 non-null    float64
 6   no2           353 non-null    float64
 7   max           353 non-null    float64
 8   critical      352 non-null    object
 9   categori      353 non-null    object
 10  lokasi_spku   353 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 33.1+ KB

In [157]:
ISPU14_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU14_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [158]:
ISPU15_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1586 entries, 0 to 1824
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1586 non-null   int64
 1   tanggal       1586 non-null   datetime64[ns]
 2   stasiun       1586 non-null   object
 3   pm10          1586 non-null   float64
 4   pm25          1518 non-null   float64
 5   so2           1586 non-null   float64
 6   co            1586 non-null   float64
 7   o3            1586 non-null   float64
 8   no2           1586 non-null   float64
 9   max           1585 non-null   float64
 10  critical      1586 non-null   object
 11  categori      1585 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 225.6+ KB

In [159]:
ISPU15_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU15_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [160]:
ISPU15_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1586 entries, 0 to 1824
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1586 non-null   int64
 1   tanggal       1586 non-null   datetime64[ns]
 2   stasiun       1586 non-null   object
 3   pm10          1586 non-null   float64
 4   pm25          1518 non-null   float64
 5   so2           1586 non-null   float64
 6   co            1586 non-null   float64
 7   o3            1586 non-null   float64
 8   no2           1586 non-null   float64
 9   max           1585 non-null   float64
 10  critical      1586 non-null   object
 11  kategori      1585 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 225.6+ KB

In [161]:
ISPU16_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       364 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   pm25          365 non-null    float64
 4   so2           365 non-null    float64
 5   co            365 non-null    float64
 6   o3            365 non-null    float64
 7   no2           365 non-null    float64
 8   max           365 non-null    float64
 9   critical      364 non-null    object
 10  categori      365 non-null    object
 11  lokasi_spku   365 non-null    object
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 34.3+ KB

In [162]:
ISPU16_not_null.rename(columns={'lokasi_spku': 'stasiun'}, inplace=True)
ISPU16_not_null.rename(columns={'categori': 'kategori'}, inplace=True)

In [163]:
for i in range(2, 17):
    globals()[f'ISPU{i}_not_null'] = clean_kolom_kategori(
        globals()[f'ISPU{i}_not_null'],
        kolom_kategori
    )

/tmp/ipython-input-2085576298.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = (
/tmp/ipython-input-2085576298.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = (
/tmp/ipython-input-2085576298.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = (
/tmp/ipython-input-2085576298.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[kolom] = df[kolom].astype('category')
/tmp/ipython-input-2085576298.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = (
/tmp/ipython-input-2085576298.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = (
/tmp/ipython-input-2085576298.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = (
/tmp/ipython-input-2085576298.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[kolom] = df[kolom].astype('category')

In [164]:
ISPU2_not_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1687 entries, 0 to 1798
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1687 non-null   int64
 1   tanggal       1687 non-null   datetime64[ns]
 2   stasiun       1687 non-null   category
 3   pm10          1687 non-null   float64
 4   pm25          1680 non-null   float64
 5   so2           1687 non-null   float64
 6   co            1687 non-null   float64
 7   o3            1687 non-null   float64
 8   no2           1687 non-null   float64
 9   max           1687 non-null   float64
 10  critical      1687 non-null   category
 11  kategori      1687 non-null   category
dtypes: category(3), datetime64[ns](1), float64(7), int64(1)
memory usage: 137.5 KB

In [165]:
ISPU16_not_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       364 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   pm25          365 non-null    float64
 4   so2           365 non-null    float64
 5   co            365 non-null    float64
 6   o3            365 non-null    float64
 7   no2           365 non-null    float64
 8   max           365 non-null    float64
 9   critical      365 non-null    category
 10  kategori      365 non-null    category
 11  stasiun       365 non-null    category
dtypes: category(3), datetime64[ns](1), float64(7), int64(1)
memory usage: 27.4 KB

# Data Tanpa PM2.5

In [166]:
ISPU1_not_null.head()

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,kategori
0,202302,2023-02-25,DKI5 KEBON JERUK JAKARTA BARAT,35.0,NaN,13.0,12.0,31.0,18.0,35.0,PM10,BAIK
1,202302,2023-02-26,DKI5 KEBON JERUK JAKARTA BARAT,23.0,NaN,14.0,9.0,32.0,11.0,32.0,O3,BAIK
2,202302,2023-02-27,DKI5 KEBON JERUK JAKARTA BARAT,20.0,NaN,13.0,8.0,33.0,13.0,33.0,O3,BAIK
3,202302,2023-02-28,DKI5 KEBON JERUK JAKARTA BARAT,30.0,NaN,21.0,11.0,28.0,18.0,30.0,PM10,BAIK
4,202303,2023-03-01,DKI1 BUNDERAN HI,38.0,44.0,50.0,8.0,19.0,27.0,50.0,3,BAIK

In [167]:
kolom_impute = ['o3', 'co']

for col in kolom_impute:
    ISPU1_not_null[col] = ISPU1_not_null[col].fillna(
        ISPU1_not_null[col].median()
    )

In [168]:
ISPU1_tanpa25 = ISPU1_not_null.drop(columns=['pm25'])

In [169]:
ISPU1_tanpa25['critical'].unique()

['PM10', 'O3', '3', '2', '1', '5', 'SO2', 'PM25']
Categories (8, object): ['1', '2', '3', '5', 'O3', 'PM10', 'PM25', 'SO2']

In [170]:
ISPU1_tanpa25.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
dtype: int64

In [171]:
ISPU1_tanpa25

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,kategori
0,202302,2023-02-25,DKI5 KEBON JERUK JAKARTA BARAT,35.0,13.0,12.0,31.0,18.0,35.0,PM10,BAIK
1,202302,2023-02-26,DKI5 KEBON JERUK JAKARTA BARAT,23.0,14.0,9.0,32.0,11.0,32.0,O3,BAIK
2,202302,2023-02-27,DKI5 KEBON JERUK JAKARTA BARAT,20.0,13.0,8.0,33.0,13.0,33.0,O3,BAIK
3,202302,2023-02-28,DKI5 KEBON JERUK JAKARTA BARAT,30.0,21.0,11.0,28.0,18.0,30.0,PM10,BAIK
4,202303,2023-03-01,DKI1 BUNDERAN HI,38.0,50.0,8.0,19.0,27.0,50.0,3,BAIK
...,...,...,...,...,...,...,...,...,...,...,...
1820,202311,2023-11-26,DKI5 KEBON JERUK,48.0,33.0,21.0,44.0,20.0,71.0,PM25,SEDANG
1821,202311,2023-11-27,DKI5 KEBON JERUK,51.0,32.0,18.0,53.0,19.0,76.0,PM25,SEDANG
1822,202311,2023-11-28,DKI5 KEBON JERUK,56.0,33.0,20.0,48.0,21.0,88.0,PM25,SEDANG
1823,202311,2023-11-29,DKI5 KEBON JERUK,56.0,32.0,18.0,56.0,18.0,88.0,PM25,SEDANG
1824,202311,2023-11-30,DKI5 KEBON JERUK,30.0,32.0,15.0,61.0,17.0,61.0,O3,SEDANG

In [172]:
ISPU2_not_null

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,kategori
0,202401,2024-01-21,DKI3 JAGAKARSA,51.0,65.0,45.0,9.0,8.0,79.0,79.0,NAN,SEDANG
1,202401,2024-01-22,DKI3 JAGAKARSA,27.0,34.0,45.0,5.0,8.0,56.0,56.0,NAN,SEDANG
3,202401,2024-01-24,DKI3 JAGAKARSA,46.0,65.0,46.0,8.0,9.0,38.0,65.0,PM25,SEDANG
4,202401,2024-01-25,DKI3 JAGAKARSA,37.0,55.0,47.0,7.0,11.0,28.0,55.0,PM25,SEDANG
5,202401,2024-01-26,DKI3 JAGAKARSA,43.0,62.0,50.0,7.0,15.0,14.0,62.0,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...,...
1794,202412,2024-12-27,DKI4 LUBANG BUAYA,44.0,29.0,21.0,11.0,17.0,14.0,44.0,PM10,BAIK
1795,202412,2024-12-28,DKI4 LUBANG BUAYA,50.0,33.0,23.0,9.0,20.0,13.0,50.0,PM10,BAIK
1796,202412,2024-12-29,DKI4 LUBANG BUAYA,53.0,37.0,23.0,12.0,19.0,14.0,53.0,PM10,SEDANG
1797,202412,2024-12-30,DKI4 LUBANG BUAYA,39.0,19.0,22.0,7.0,22.0,11.0,39.0,PM10,BAIK
1798,202412,2024-12-31,DKI4 LUBANG BUAYA,27.0,15.0,21.0,6.0,18.0,8.0,27.0,PM10,BAIK

In [173]:

# 1. Daftar kolom polutan (yang tersedia)
polutan_cols = ['pm10', 'pm25', 'co', 'o3', 'so2', 'no2']
polutan_cols = [c for c in polutan_cols if c in ISPU2_not_null.columns]

# 2. Pastikan kolom polutan numerik
ISPU2_not_null[polutan_cols] = ISPU2_not_null[polutan_cols].apply(
    pd.to_numeric, errors='coerce'
)

# 3. Isi critical HANYA jika masih NaN
mask = ISPU2_not_null['critical'].isna()

ISPU2_not_null.loc[mask, 'critical'] = ISPU2_not_null.loc[mask, polutan_cols].idxmax(axis=1)

In [174]:
ISPU2_tanpa25 = ISPU2_not_null.drop(columns=['pm25'])

In [175]:
ISPU2_tanpa25.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
dtype: int64

In [176]:
ISPU3_not_null

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,kategori
0,202504,2025-04-24,DKI5 KEBON JERUK,16.0,50.0,18.0,3.0,16.0,4.0,50.0,PM25,BAIK
1,202504,2025-04-25,DKI5 KEBON JERUK,23.0,81.0,19.0,9.0,24.0,3.0,81.0,PM25,SEDANG
2,202504,2025-04-26,DKI5 KEBON JERUK,30.0,77.0,20.0,11.0,29.0,3.0,77.0,PM25,SEDANG
3,202504,2025-04-27,DKI5 KEBON JERUK,31.0,85.0,21.0,12.0,47.0,4.0,85.0,PM25,SEDANG
4,202504,2025-04-28,DKI5 KEBON JERUK,24.0,78.0,20.0,9.0,37.0,4.0,78.0,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...,...
1209,202508,2025-08-30,DKI3 JAGAKARSA,21.0,59.0,53.0,8.0,23.0,46.0,59.0,PM25,SEDANG
1210,202508,2025-08-31,DKI3 JAGAKARSA,28.0,60.0,53.0,8.0,19.0,39.0,60.0,PM25,SEDANG
1211,202508,2025-08-01,DKI4 LUBANG BUAYA,63.0,89.0,30.0,7.0,28.0,16.0,89.0,PM25,SEDANG
1212,202508,2025-08-02,DKI4 LUBANG BUAYA,73.0,105.0,31.0,11.0,25.0,21.0,105.0,PM25,TIDAK SEHAT
1214,202508,2025-08-04,DKI4 LUBANG BUAYA,63.0,84.0,27.0,14.0,26.0,26.0,84.0,PM25,SEDANG

In [177]:
ISPU3_not_null = ISPU3_not_null.dropna(subset=['pm25', 'critical'], how='all')

In [178]:
ISPU3_not_null.isnull().sum()

periode_data     0
tanggal          0
stasiun          0
pm10             0
pm25            15
so2              0
co               0
o3               0
no2              0
max              0
critical         0
kategori         0
dtype: int64

In [179]:

# 1. Daftar kolom polutan (yang tersedia)
polutan_cols = ['pm10', 'pm25', 'co', 'o3', 'so2', 'no2']
polutan_cols = [c for c in polutan_cols if c in ISPU3_not_null.columns]

# 2. Pastikan kolom polutan numerik
ISPU3_not_null[polutan_cols] = ISPU3_not_null[polutan_cols].apply(
    pd.to_numeric, errors='coerce'
)

# 3. Isi critical HANYA jika masih NaN
mask = ISPU3_not_null['critical'].isna()

ISPU3_not_null.loc[mask, 'critical'] = ISPU3_not_null.loc[mask, polutan_cols].idxmax(axis=1)

In [180]:
ISPU3_not_null.isnull().sum()

periode_data     0
tanggal          0
stasiun          0
pm10             0
pm25            15
so2              0
co               0
o3               0
no2              0
max              0
critical         0
kategori         0
dtype: int64

In [181]:
ISPU3_tanpa25 = ISPU3_not_null.drop(columns=['pm25'])

In [182]:
ISPU4_not_null

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,kategori
47,201002,2010-02-02,DKI1 (BUNDERAN HI),50.0,4.0,30.0,23.0,12.0,50.0,PM10,BAIK
48,201002,2010-02-03,DKI1 (BUNDERAN HI),49.0,7.0,33.0,57.0,23.0,57.0,O3,SEDANG
49,201002,2010-02-04,DKI1 (BUNDERAN HI),59.0,9.0,38.0,75.0,26.0,75.0,O3,SEDANG
50,201002,2010-02-05,DKI1 (BUNDERAN HI),63.0,7.0,39.0,41.0,23.0,63.0,PM10,SEDANG
51,201002,2010-02-06,DKI1 (BUNDERAN HI),65.0,8.0,59.0,24.0,15.0,65.0,PM10,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
1775,201012,2010-12-13,DKI4 (LUBANG BUAYA),67.0,2.0,18.0,43.0,7.0,67.0,PM10,SEDANG
1776,201012,2010-12-14,DKI4 (LUBANG BUAYA),82.0,3.0,27.0,33.0,11.0,82.0,PM10,SEDANG
1784,201012,2010-12-22,DKI4 (LUBANG BUAYA),55.0,1.0,9.0,29.0,7.0,55.0,PM10,SEDANG
1785,201012,2010-12-23,DKI4 (LUBANG BUAYA),59.0,2.0,18.0,27.0,6.0,59.0,PM10,SEDANG
1786,201012,2010-12-24,DKI4 (LUBANG BUAYA),54.0,3.0,20.0,122.0,13.0,122.0,O3,TIDAK SEHAT

In [183]:
ISPU4_not_null.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
dtype: int64

In [184]:
ISPU5_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,kategori,stasiun
0,201105,2011-05-01,71.0,18.0,54.0,88.0,31.0,88.0,O3,SEDANG,DKI1
1,201105,2011-05-02,61.0,19.0,35.0,98.0,29.0,98.0,O3,SEDANG,DKI4
2,201105,2011-05-03,69.0,22.0,31.0,69.0,28.0,69.0,PM10,SEDANG,DKI1
3,201105,2011-05-04,63.0,18.0,26.0,47.0,17.0,63.0,PM10,SEDANG,DKI4
4,201105,2011-05-05,76.0,17.0,28.0,63.0,20.0,76.0,PM10,SEDANG,DKI4
...,...,...,...,...,...,...,...,...,...,...,...
360,201111,2011-11-26,79.0,19.0,33.0,126.0,15.0,126.0,O3,TIDAK SEHAT,DKI2
361,201111,2011-11-27,74.0,12.0,23.0,133.0,13.0,133.0,O3,TIDAK SEHAT,DKI2
362,201111,2011-11-28,134.0,27.0,35.0,159.0,26.0,159.0,O3,TIDAK SEHAT,DKI2
363,201111,2011-11-29,91.0,23.0,32.0,104.0,19.0,104.0,O3,TIDAK SEHAT,DKI2
364,201111,2011-11-30,75.0,20.0,28.0,164.0,20.0,164.0,O3,TIDAK SEHAT,DKI2

In [185]:
ISPU5_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [186]:
ISPU6_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,kategori,stasiun
0,201201,2012-01-01,52.0,18.0,39.0,63.0,7.0,63.0,O3,SEDANG,DKI2
1,201201,2012-01-02,49.0,22.0,28.0,55.0,11.0,55.0,O3,SEDANG,DKI2
2,201201,2012-01-03,65.0,15.0,42.0,86.0,22.0,86.0,O3,SEDANG,DKI1
3,201201,2012-01-04,69.0,20.0,55.0,97.0,20.0,97.0,O3,SEDANG,DKI1
4,201201,2012-01-05,67.0,14.0,39.0,157.0,25.0,157.0,O3,TIDAK SEHAT,DKI2
...,...,...,...,...,...,...,...,...,...,...,...
361,201211,2012-11-26,58.0,34.0,40.0,203.0,18.0,203.0,O3,SANGAT TIDAK SEHAT,DKI2
362,201211,2012-11-27,84.0,37.0,52.0,215.0,18.0,215.0,O3,SANGAT TIDAK SEHAT,DKI2
363,201211,2012-11-28,62.0,30.0,47.0,227.0,16.0,227.0,O3,SANGAT TIDAK SEHAT,DKI2
364,201211,2012-11-29,69.0,32.0,49.0,218.0,22.0,218.0,O3,SANGAT TIDAK SEHAT,DKI2
365,201211,2012-11-30,76.0,30.0,76.0,137.0,22.0,137.0,O3,TIDAK SEHAT,DKI2

In [187]:
ISPU6_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [188]:
ISPU7_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,kategori,stasiun
0,201301,2013-01-01,75.0,4.0,27.0,135.0,10.0,135.0,O3,TIDAK SEHAT,DKI2
1,201301,2013-01-02,35.0,4.0,26.0,192.0,8.0,192.0,O3,TIDAK SEHAT,DKI2
2,201301,2013-01-03,61.0,5.0,36.0,195.0,9.0,195.0,O3,TIDAK SEHAT,DKI2
3,201301,2013-01-04,39.0,4.0,13.0,210.0,10.0,210.0,O3,SANGAT TIDAK SEHAT,DKI2
4,201301,2013-01-05,53.0,5.0,14.0,111.0,8.0,111.0,O3,TIDAK SEHAT,DKI2
...,...,...,...,...,...,...,...,...,...,...,...
360,201312,2013-12-27,72.0,10.0,61.0,71.0,17.0,72.0,PM10,SEDANG,DKI4
361,201312,2013-12-28,67.0,7.0,50.0,65.0,11.0,67.0,PM10,SEDANG,DKI4
362,201312,2013-12-29,53.0,8.0,21.0,63.0,12.0,63.0,O3,SEDANG,DKI4
363,201312,2013-12-30,41.0,10.0,26.0,67.0,12.0,67.0,O3,SEDANG,DKI4
364,201312,2013-12-31,28.0,6.0,26.0,69.0,13.0,69.0,O3,SEDANG,DKI4

In [189]:
ISPU7_not_null.isnull().sum()

periode_data     0
tanggal         30
pm10             0
so2              0
co               0
o3               0
no2              0
max              0
critical         0
kategori         0
stasiun          0
dtype: int64

In [190]:
ISPU7_not_null.loc[294]

periode_data                 201311
tanggal         2013-11-21 00:00:00
pm10                           57.0
so2                            22.0
co                             28.0
o3                             58.0
no2                            16.0
max                            58.0
critical                         O3
kategori                     SEDANG
stasiun                        DKI2
Name: 294, dtype: object

In [191]:
ISPU7_not_null[ISPU7_not_null['tanggal'].isna()]

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,kategori,stasiun
295,201309,NaT,74.0,23.0,33.0,67.0,13.0,74.0,PM10,SEDANG,DKI4
296,201309,NaT,76.0,29.0,30.0,109.0,15.0,109.0,O3,TIDAK SEHAT,DKI3
297,201309,NaT,82.0,22.0,42.0,125.0,24.0,125.0,O3,TIDAK SEHAT,DKI5
298,201309,NaT,75.0,19.0,33.0,98.0,19.0,98.0,O3,SEDANG,DKI2
299,201309,NaT,77.0,20.0,32.0,139.0,24.0,139.0,O3,TIDAK SEHAT,DKI5
300,201309,NaT,67.0,18.0,31.0,123.0,19.0,123.0,O3,TIDAK SEHAT,DKI4
301,201309,NaT,70.0,20.0,32.0,78.0,20.0,78.0,O3,SEDANG,DKI4
302,201309,NaT,63.0,23.0,26.0,92.0,15.0,92.0,O3,SEDANG,DKI3
303,201309,NaT,68.0,24.0,34.0,90.0,20.0,90.0,O3,SEDANG,DKI3
304,201309,NaT,80.0,44.0,42.0,98.0,21.0,98.0,O3,SEDANG,DKI3
305,201309,NaT,77.0,27.0,33.0,105.0,18.0,105.0,O3,TIDAK SEHAT,DKI3
306,201309,NaT,76.0,33.0,29.0,70.0,17.0,76.0,PM10,SEDANG,DKI4
307,201309,NaT,83.0,40.0,32.0,114.0,22.0,114.0,O3,TIDAK SEHAT,DKI3
308,201309,NaT,71.0,30.0,28.0,113.0,19.0,113.0,O3,TIDAK SEHAT,DKI4
309,201309,NaT,66.0,25.0,35.0,98.0,17.0,98.0,O3,SEDANG,DKI3
310,201309,NaT,54.0,21.0,35.0,63.0,17.0,63.0,O3,SEDANG,DKI5
311,201309,NaT,68.0,30.0,34.0,138.0,26.0,138.0,O3,TIDAK SEHAT,DKI5
312,201309,NaT,77.0,19.0,30.0,110.0,27.0,110.0,O3,TIDAK SEHAT,DKI4
313,201309,NaT,71.0,37.0,30.0,91.0,19.0,91.0,O3,SEDANG,DKI5
314,201309,NaT,71.0,34.0,32.0,84.0,21.0,84.0,O3,SEDANG,DKI3
315,201309,NaT,70.0,26.0,25.0,134.0,19.0,134.0,O3,TIDAK SEHAT,DKI5
316,201309,NaT,67.0,25.0,33.0,107.0,17.0,107.0,O3,TIDAK SEHAT,DKI3
317,201309,NaT,69.0,27.0,30.0,128.0,27.0,128.0,O3,TIDAK SEHAT,DKI5
318,201309,NaT,76.0,30.0,27.0,79.0,22.0,79.0,O3,SEDANG,DKI5
319,201309,NaT,76.0,31.0,30.0,117.0,30.0,117.0,O3,TIDAK SEHAT,DKI5
320,201309,NaT,67.0,22.0,26.0,100.0,19.0,100.0,O3,SEDANG,DKI4
321,201309,NaT,65.0,31.0,31.0,118.0,25.0,118.0,O3,TIDAK SEHAT,DKI4
322,201309,NaT,72.0,37.0,26.0,91.0,18.0,91.0,O3,SEDANG,DKI3
323,201309,NaT,77.0,37.0,26.0,88.0,12.0,88.0,O3,SEDANG,DKI4
324,201309,NaT,73.0,33.0,29.0,69.0,18.0,73.0,PM10,SEDANG,DKI5

In [192]:
ISPU7_not_null = ISPU7_not_null.dropna(subset=['tanggal'])

In [193]:
ISPU7_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [194]:
ISPU8_not_null.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
dtype: int64

In [195]:
ISPU9_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [196]:
ISPU10_not_null.isnull().sum()

periode_data     0
tanggal         62
stasiun          0
pm10             0
so2              0
co               0
o3               0
no2              0
max              0
critical         0
kategori         0
dtype: int64

In [197]:
ISPU10_not_null = ISPU10_not_null.dropna(subset=['tanggal'])

In [198]:
ISPU11_not_null.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
dtype: int64

In [199]:
ISPU12_not_null.isnull().sum()

periode_data      0
tanggal         221
pm10              0
so2               0
co                0
o3                0
no2               0
max               0
critical          0
kategori          0
stasiun           0
dtype: int64

In [200]:
ISPU12_not_null = ISPU12_not_null.dropna(subset=['tanggal'])

In [201]:
ISPU13_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [202]:
ISPU14_not_null.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [203]:
ISPU14_not_null

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,kategori,stasiun
0,202005,2020-05-01,55.0,26.0,21.0,83.0,10.0,83.0,O3,SEDANG,DKI5
1,202005,2020-05-02,36.0,22.0,12.0,80.0,9.0,80.0,O3,SEDANG,DKI5
2,202005,2020-05-03,65.0,34.0,35.0,49.0,11.0,65.0,PM10,SEDANG,DKI5
3,202005,2020-05-04,53.0,21.0,14.0,75.0,8.0,75.0,O3,SEDANG,DKI5
4,202005,2020-05-05,53.0,22.0,18.0,73.0,9.0,73.0,O3,SEDANG,DKI5
...,...,...,...,...,...,...,...,...,...,...,...
361,202010,2020-10-27,52.0,54.0,17.0,34.0,30.0,70.0,PM25,SEDANG,DKI4
362,202010,2020-10-28,66.0,54.0,29.0,32.0,33.0,89.0,PM25,SEDANG,DKI5
363,202010,2020-10-29,57.0,55.0,15.0,35.0,26.0,87.0,PM25,SEDANG,DKI4
364,202010,2020-10-30,63.0,55.0,18.0,34.0,19.0,108.0,PM25,TIDAK SEHAT,DKI4
365,202010,2020-10-31,45.0,55.0,15.0,29.0,20.0,72.0,NAN,SEDANG,0

In [204]:
ISPU15_not_null.isnull().sum()

periode_data     0
tanggal          0
stasiun          0
pm10             0
pm25            68
so2              0
co               0
o3               0
no2              0
max              1
critical         0
kategori         0
dtype: int64

In [205]:
polutan_cols = ['pm10', 'co', 'o3', 'so2', 'no2']
polutan_cols = [c for c in polutan_cols if c in ISPU15_not_null.columns]
mask = ISPU15_not_null['max'].isna()

ISPU15_not_null.loc[mask, 'max'] = (
    ISPU15_not_null.loc[mask, polutan_cols]
    .max(axis=1)
)

In [206]:
ISPU15_tanpa25 = ISPU15_not_null.drop(columns=['pm25'])

In [207]:
ISPU16_not_null.isnull().sum()

periode_data    0
tanggal         1
pm10            0
pm25            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [208]:
ISPU16_not_null = ISPU16_not_null.dropna(subset=['tanggal'])
ISPU16_tanpa25 = ISPU16_not_null.drop(columns=['pm25'])

In [209]:
ISPU16_tanpa25.isnull().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
stasiun         0
dtype: int64

In [210]:
list_ispu = [
    ISPU1_tanpa25, ISPU2_tanpa25, ISPU3_tanpa25, ISPU4_not_null,
    ISPU5_not_null, ISPU6_not_null, ISPU7_not_null, ISPU8_not_null,
    ISPU9_not_null, ISPU10_not_null, ISPU11_not_null, ISPU12_not_null,
    ISPU13_not_null, ISPU14_not_null, ISPU15_tanpa25, ISPU16_tanpa25
]

In [211]:
for i, df in enumerate(list_ispu, start=1):
    print(f'\n===== ISPU{i} INFO =====')
    df.info()

===== ISPU1 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 1536 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1536 non-null   int64
 1   tanggal       1536 non-null   datetime64[ns]
 2   stasiun       1536 non-null   category
 3   pm10          1536 non-null   float64
 4   so2           1536 non-null   float64
 5   co            1536 non-null   float64
 6   o3            1536 non-null   float64
 7   no2           1536 non-null   float64
 8   max           1536 non-null   float64
 9   critical      1536 non-null   category
 10  kategori      1536 non-null   category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 113.3 KB

===== ISPU2 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 1687 entries, 0 to 1798
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1687 non-null   int64
 1   tanggal       1687 non-null   datetime64[ns]
 2   stasiun       1687 non-null   category
 3   pm10          1687 non-null   float64
 4   so2           1687 non-null   float64
 5   co            1687 non-null   float64
 6   o3            1687 non-null   float64
 7   no2           1687 non-null   float64
 8   max           1687 non-null   float64
 9   critical      1687 non-null   category
 10  kategori      1687 non-null   category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 124.3 KB

===== ISPU3 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 1096 entries, 0 to 1214
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1096 non-null   int64
 1   tanggal       1096 non-null   datetime64[ns]
 2   stasiun       1096 non-null   category
 3   pm10          1096 non-null   float64
 4   so2           1096 non-null   float64
 5   co            1096 non-null   float64
 6   o3            1096 non-null   float64
 7   no2           1096 non-null   float64
 8   max           1096 non-null   float64
 9   critical      1096 non-null   category
 10  kategori      1096 non-null   category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 81.0 KB

===== ISPU4 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 467 entries, 47 to 1786
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  467 non-null    int64
 1   tanggal       467 non-null    datetime64[ns]
 2   stasiun       467 non-null    category
 3   pm10          467 non-null    float64
 4   so2           467 non-null    float64
 5   co            467 non-null    float64
 6   o3            467 non-null    float64
 7   no2           467 non-null    float64
 8   max           467 non-null    float64
 9   critical      467 non-null    category
 10  kategori      467 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 50.9 KB

===== ISPU5 INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   so2           365 non-null    float64
 4   co            365 non-null    float64
 5   o3            365 non-null    float64
 6   no2           365 non-null    float64
 7   max           365 non-null    float64
 8   critical      365 non-null    category
 9   kategori      365 non-null    category
 10  stasiun       365 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 24.5 KB

===== ISPU6 INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  366 non-null    int64
 1   tanggal       366 non-null    datetime64[ns]
 2   pm10          366 non-null    float64
 3   so2           366 non-null    float64
 4   co            366 non-null    float64
 5   o3            366 non-null    float64
 6   no2           366 non-null    float64
 7   max           366 non-null    float64
 8   critical      366 non-null    category
 9   kategori      366 non-null    category
 10  stasiun       366 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 24.6 KB

===== ISPU7 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 335 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  335 non-null    int64
 1   tanggal       335 non-null    datetime64[ns]
 2   pm10          335 non-null    float64
 3   so2           335 non-null    float64
 4   co            335 non-null    float64
 5   o3            335 non-null    float64
 6   no2           335 non-null    float64
 7   max           335 non-null    float64
 8   critical      335 non-null    category
 9   kategori      335 non-null    category
 10  stasiun       335 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 25.1 KB

===== ISPU8 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 1501 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1501 non-null   int64
 1   tanggal       1501 non-null   datetime64[ns]
 2   stasiun       1501 non-null   category
 3   pm10          1501 non-null   float64
 4   so2           1501 non-null   float64
 5   co            1501 non-null   float64
 6   o3            1501 non-null   float64
 7   no2           1501 non-null   float64
 8   max           1501 non-null   float64
 9   critical      1501 non-null   category
 10  kategori      1501 non-null   category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 142.8 KB

===== ISPU9 INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    datetime64[ns]
 2   pm10          365 non-null    float64
 3   so2           365 non-null    float64
 4   co            365 non-null    float64
 5   o3            365 non-null    float64
 6   no2           365 non-null    float64
 7   max           365 non-null    float64
 8   critical      365 non-null    category
 9   kategori      365 non-null    category
 10  stasiun       365 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 24.5 KB

===== ISPU10 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 1484 entries, 0 to 1807
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1484 non-null   int64
 1   tanggal       1484 non-null   datetime64[ns]
 2   stasiun       1484 non-null   category
 3   pm10          1484 non-null   float64
 4   so2           1484 non-null   float64
 5   co            1484 non-null   float64
 6   o3            1484 non-null   float64
 7   no2           1484 non-null   float64
 8   max           1484 non-null   float64
 9   critical      1484 non-null   category
 10  kategori      1484 non-null   category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 109.3 KB

===== ISPU11 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 1534 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1534 non-null   int64
 1   tanggal       1534 non-null   datetime64[ns]
 2   stasiun       1534 non-null   category
 3   pm10          1534 non-null   float64
 4   so2           1534 non-null   float64
 5   co            1534 non-null   float64
 6   o3            1534 non-null   float64
 7   no2           1534 non-null   float64
 8   max           1534 non-null   float64
 9   critical      1534 non-null   category
 10  kategori      1534 non-null   category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 112.9 KB

===== ISPU12 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 144 entries, 0 to 345
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  144 non-null    int64
 1   tanggal       144 non-null    datetime64[ns]
 2   pm10          144 non-null    float64
 3   so2           144 non-null    float64
 4   co            144 non-null    float64
 5   o3            144 non-null    float64
 6   no2           144 non-null    float64
 7   max           144 non-null    float64
 8   critical      144 non-null    category
 9   kategori      144 non-null    category
 10  stasiun       144 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 11.2 KB

===== ISPU13 INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  345 non-null    int64
 1   tanggal       345 non-null    datetime64[ns]
 2   pm10          345 non-null    float64
 3   so2           345 non-null    float64
 4   co            345 non-null    float64
 5   o3            345 non-null    float64
 6   no2           345 non-null    float64
 7   max           345 non-null    float64
 8   critical      345 non-null    category
 9   kategori      345 non-null    category
 10  stasiun       345 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 23.2 KB

===== ISPU14 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 353 entries, 0 to 365
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  353 non-null    int64
 1   tanggal       353 non-null    datetime64[ns]
 2   pm10          353 non-null    float64
 3   so2           353 non-null    float64
 4   co            353 non-null    float64
 5   o3            353 non-null    float64
 6   no2           353 non-null    float64
 7   max           353 non-null    float64
 8   critical      353 non-null    category
 9   kategori      353 non-null    category
 10  stasiun       353 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 26.8 KB

===== ISPU15 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 1586 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  1586 non-null   int64
 1   tanggal       1586 non-null   datetime64[ns]
 2   stasiun       1586 non-null   category
 3   pm10          1586 non-null   float64
 4   so2           1586 non-null   float64
 5   co            1586 non-null   float64
 6   o3            1586 non-null   float64
 7   no2           1586 non-null   float64
 8   max           1586 non-null   float64
 9   critical      1586 non-null   category
 10  kategori      1586 non-null   category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 181.3 KB

===== ISPU16 INFO =====
<class 'pandas.core.frame.DataFrame'>
Index: 364 entries, 1 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  364 non-null    int64
 1   tanggal       364 non-null    datetime64[ns]
 2   pm10          364 non-null    float64
 3   so2           364 non-null    float64
 4   co            364 non-null    float64
 5   o3            364 non-null    float64
 6   no2           364 non-null    float64
 7   max           364 non-null    float64
 8   critical      364 non-null    category
 9   kategori      364 non-null    category
 10  stasiun       364 non-null    category
dtypes: category(3), datetime64[ns](1), float64(6), int64(1)
memory usage: 27.2 KB

In [212]:
ISPU_tanpa25 = pd.concat(
    list_ispu,
    axis=0,          # gabung ke bawah (baris)
    ignore_index=True
)

In [213]:
ISPU_tanpa25.shape
ISPU_tanpa25.info()
ISPU_tanpa25.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13528 entries, 0 to 13527
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  13528 non-null  int64
 1   tanggal       13528 non-null  datetime64[ns]
 2   stasiun       13528 non-null  object
 3   pm10          13528 non-null  float64
 4   so2           13528 non-null  float64
 5   co            13528 non-null  float64
 6   o3            13528 non-null  float64
 7   no2           13528 non-null  float64
 8   max           13528 non-null  float64
 9   critical      13528 non-null  object
 10  kategori      13528 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 1.1+ MB

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,kategori
0,202302,2023-02-25,DKI5 KEBON JERUK JAKARTA BARAT,35.0,13.0,12.0,31.0,18.0,35.0,PM10,BAIK
1,202302,2023-02-26,DKI5 KEBON JERUK JAKARTA BARAT,23.0,14.0,9.0,32.0,11.0,32.0,O3,BAIK
2,202302,2023-02-27,DKI5 KEBON JERUK JAKARTA BARAT,20.0,13.0,8.0,33.0,13.0,33.0,O3,BAIK
3,202302,2023-02-28,DKI5 KEBON JERUK JAKARTA BARAT,30.0,21.0,11.0,28.0,18.0,30.0,PM10,BAIK
4,202303,2023-03-01,DKI1 BUNDERAN HI,38.0,50.0,8.0,19.0,27.0,50.0,3,BAIK

In [214]:
ISPU_tanpa25['critical'].unique()

array(['PM10', 'O3', '3', '2', '1', '5', 'SO2', 'PM25', 'NAN', 'CO',
       'NO2', '4', 'BAIK', 'PM2,5'], dtype=object)

In [215]:
ISPU_tanpa25['kategori'].unique()

array(['BAIK', 'SEDANG', 'TIDAK SEHAT', 'SANGAT TIDAK SEHAT', 'BERBAHAYA',
       'O3', 'NAN'], dtype=object)

In [216]:
ISPU_tanpa25['stasiun'].unique()

array(['DKI5 KEBON JERUK JAKARTA BARAT', 'DKI1 BUNDERAN HI',
       'DKI2 KELAPA GADING', 'DKI3 JAGAKARSA', 'DKI4 LUBANG BUAYA',
       'DKI5 KEBON JERUK', 'DKI1 BUNDARAN HOTEL INDONESIA (HI)',
       'DKI1 BUNDARAN HOTEL INDONESIA HI', 'DKI1 (BUNDERAN HI)',
       'DKI3 (JAGAKARSA)', 'DKI4 (LUBANG BUAYA)', 'DKI2 (KELAPA GADING)',
       'DKI1', 'DKI4', 'DKI2', 'DKI3', 'DKI5', 'DKI5 (KEBON JERUK)',
       'DKI5 (KEBON JERUK) JAKARTA BARAT', 'SEDANG', 'BAIK',
       'TIDAK SEHAT', '0'], dtype=object)

In [217]:
ISPU_tanpa25[ISPU_tanpa25['stasiun'] == 'SEDANG']

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,kategori
11309,202003,2020-03-06,SEDANG,24.0,17.0,52.0,95.0,3.0,95.0,4,O3
11310,202003,2020-03-07,SEDANG,34.0,27.0,40.0,54.0,7.0,54.0,4,O3
11311,202003,2020-03-08,SEDANG,30.0,24.0,40.0,58.0,5.0,58.0,4,O3
11312,202003,2020-03-09,SEDANG,52.0,22.0,38.0,59.0,7.0,59.0,4,O3
11315,202003,2020-03-12,SEDANG,34.0,20.0,46.0,63.0,4.0,63.0,4,O3
11316,202003,2020-03-13,SEDANG,44.0,19.0,58.0,72.0,10.0,72.0,4,O3
11317,202003,2020-03-14,SEDANG,32.0,19.0,51.0,69.0,6.0,69.0,4,O3
11319,202003,2020-03-16,SEDANG,53.0,18.0,63.0,92.0,8.0,92.0,4,O3
11320,202003,2020-03-17,SEDANG,48.0,19.0,62.0,70.0,9.0,70.0,4,O3
11322,202003,2020-03-19,SEDANG,45.0,18.0,35.0,90.0,6.0,90.0,4,O3
11324,202003,2020-03-30,SEDANG,65.0,14.0,11.0,91.0,7.0,91.0,4,O3
11325,202003,2020-03-31,SEDANG,53.0,9.0,10.0,76.0,5.0,76.0,4,O3
11326,202003,2020-03-31,SEDANG,47.0,11.0,14.0,96.0,6.0,96.0,4,O3

In [218]:
ISPU_tanpa25['critical'] = (
    ISPU_tanpa25['critical']
    .astype(str)
    .str.strip()
    .str.lower()

)
import numpy as np

invalid_values = [
    '1', '2', '3', '4', '5',
    'baik',
    'nan', 'none'
]

ISPU_tanpa25['critical'] = ISPU_tanpa25['critical'].replace(
    invalid_values,
    np.nan
)

In [219]:
ISPU_tanpa25[ISPU_tanpa25['critical'].isna()]

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,kategori
4,202303,2023-03-01,DKI1 BUNDERAN HI,38.0,50.0,8.0,19.0,27.0,50.0,NaN,BAIK
5,202303,2023-03-02,DKI1 BUNDERAN HI,29.0,47.0,11.0,21.0,27.0,47.0,NaN,BAIK
6,202303,2023-03-03,DKI1 BUNDERAN HI,38.0,49.0,9.0,16.0,25.0,49.0,NaN,BAIK
7,202303,2023-03-04,DKI1 BUNDERAN HI,31.0,50.0,11.0,18.0,21.0,50.0,NaN,BAIK
8,202303,2023-03-05,DKI1 BUNDERAN HI,33.0,47.0,11.0,21.0,22.0,47.0,NaN,BAIK
...,...,...,...,...,...,...,...,...,...,...,...
11325,202003,2020-03-31,SEDANG,53.0,9.0,10.0,76.0,5.0,76.0,NaN,O3
11326,202003,2020-03-31,SEDANG,47.0,11.0,14.0,96.0,6.0,96.0,NaN,O3
11577,202010,2020-10-31,0,45.0,55.0,15.0,29.0,20.0,72.0,NaN,SEDANG
13103,202112,2021-12-03,DKI1 (BUNDERAN HI),49.0,9.0,19.0,7.0,49.0,49.0,NaN,NAN
13463,202205,2022-05-31,0,63.0,44.0,44.0,59.0,44.0,100.0,NaN,SEDANG

In [220]:
# 1. Daftar kolom polutan (yang tersedia)
polutan_cols = ['pm10', 'pm25', 'co', 'o3', 'so2', 'no2']
polutan_cols = [c for c in polutan_cols if c in ISPU_tanpa25.columns]

# 2. Pastikan kolom polutan numerik
ISPU_tanpa25[polutan_cols] = ISPU_tanpa25[polutan_cols].apply(
    pd.to_numeric, errors='coerce'
)

# 3. Isi critical HANYA jika masih NaN
mask = ISPU_tanpa25['critical'].isna()

ISPU_tanpa25.loc[mask, 'critical'] = ISPU_tanpa25.loc[mask, polutan_cols].idxmax(axis=1)

In [221]:
ISPU_tanpa25[ISPU_tanpa25['critical'].isna()]

Empty DataFrame
Columns: [periode_data, tanggal, stasiun, pm10, so2, co, o3, no2, max, critical, kategori]
Index: []

In [222]:
ISPU_tanpa25['critical'].unique()

array(['pm10', 'o3', 'so2', 'pm25', 'no2', 'co', 'pm2,5'], dtype=object)

In [223]:
ISPU_tanpa25['critical'] = ISPU_tanpa25['critical'].replace(
    'pm2,5', 'pm25'
)

In [224]:
ISPU_tanpa25['critical'].unique()

array(['pm10', 'o3', 'so2', 'pm25', 'no2', 'co'], dtype=object)

In [225]:


ISPU_tanpa25['kategori'] = (
    ISPU_tanpa25['kategori']
    .astype(str)
    .str.strip()
    .str.upper()
)
invalid_kategori = ['O3', 'NAN', 'NONE','nan']

ISPU_tanpa25['kategori'] = ISPU_tanpa25['kategori'].replace(
    invalid_kategori,
    np.nan
)

ISPU_tanpa25['kategori'].unique()

array(['BAIK', 'SEDANG', 'TIDAK SEHAT', 'SANGAT TIDAK SEHAT', 'BERBAHAYA',
       nan], dtype=object)

In [226]:
ISPU_tanpa25.isnull().sum()

periode_data     0
tanggal          0
stasiun          0
pm10             0
so2              0
co               0
o3               0
no2              0
max              0
critical         0
kategori        19
dtype: int64

In [227]:
print("Jumlah kategori null:", ISPU_tanpa25['kategori'].isna().sum())
print(ISPU_tanpa25['kategori'].value_counts(dropna=False))

Jumlah kategori null: 19
kategori
SEDANG                9388
TIDAK SEHAT           2095
BAIK                  1844
SANGAT TIDAK SEHAT     181
NaN                     19
BERBAHAYA                1
Name: count, dtype: int64

In [228]:

# 1. Pastikan kolom max bertipe numerik
ISPU_tanpa25['max'] = pd.to_numeric(ISPU_tanpa25['max'], errors='coerce')

# 2. Pastikan kategori bersih (hindari string 'NAN')
ISPU_tanpa25['kategori'] = (
    ISPU_tanpa25['kategori']
    .replace(['NAN', 'nan', 'None', 'NONE', ''], np.nan)
)

# 3. Fungsi penentuan kategori ISPU
def kategori_ispu(x):
    if pd.isna(x):
        return np.nan
    elif x <= 50:
        return 'BAIK'
    elif x <= 100:
        return 'SEDANG'
    elif x <= 200:
        return 'TIDAK SEHAT'
    elif x <= 300:
        return 'SANGAT TIDAK SEHAT'
    else:
        return 'BERBAHAYA'

# 4. Mask: hanya kategori NULL & max ADA
mask = ISPU_tanpa25['kategori'].isna() & ISPU_tanpa25['max'].notna()

# 5. Isi kategori NULL saja
ISPU_tanpa25.loc[mask, 'kategori'] = (
    ISPU_tanpa25.loc[mask, 'max']
    .apply(kategori_ispu)
)

# 6. (Opsional tapi disarankan) Jadikan category dtype
kategori_order = [
    'BAIK',
    'SEDANG',
    'TIDAK SEHAT',
    'SANGAT TIDAK SEHAT',
    'BERBAHAYA'
]

ISPU_tanpa25['kategori'] = pd.Categorical(
    ISPU_tanpa25['kategori'],
    categories=kategori_order,
    ordered=True
)

# 7. Cek hasil akhir
print("Jumlah kategori null:", ISPU_tanpa25['kategori'].isna().sum())
print(ISPU_tanpa25['kategori'].value_counts(dropna=False))

Jumlah kategori null: 0
kategori
SEDANG                9401
TIDAK SEHAT           2098
BAIK                  1847
SANGAT TIDAK SEHAT     181
BERBAHAYA                1
Name: count, dtype: int64

In [229]:
import numpy as np
import pandas as pd

# 1. Uppercase + strip
ISPU_tanpa25['stasiun'] = (
    ISPU_tanpa25['stasiun']
    .astype(str)
    .str.upper()
    .str.strip()
)

# 2. Buang nilai yang jelas bukan stasiun
invalid_stasiun = ['BAIK', 'SEDANG', 'TIDAK SEHAT', '0', 'NAN', 'NONE']

ISPU_tanpa25['stasiun'] = ISPU_tanpa25['stasiun'].replace(
    invalid_stasiun,
    np.nan
)

# 3. Ambil kode DKI (DKI1–DKI5) dari string
ISPU_tanpa25['stasiun'] = (
    ISPU_tanpa25['stasiun']
    .str.extract(r'(DKI[1-5])')
)

# 4. Jadikan category (opsional tapi disarankan)
ISPU_tanpa25['stasiun'] = ISPU_tanpa25['stasiun'].astype('category')

# 5. Cek hasil
print(ISPU_tanpa25['stasiun'].unique())
print("Jumlah null:", ISPU_tanpa25['stasiun'].isna().sum())

['DKI5', 'DKI1', 'DKI2', 'DKI3', 'DKI4', NaN]
Categories (5, object): ['DKI1', 'DKI2', 'DKI3', 'DKI4', 'DKI5']
Jumlah null: 20

In [230]:
ISPU_tanpa25= ISPU_tanpa25.dropna()

In [231]:
ISPU_tanpa25.isnull().sum()

periode_data    0
tanggal         0
stasiun         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
kategori        0
dtype: int64

In [244]:
ISPU_tanpa25.duplicated().sum()

np.int64(1)

In [245]:
ISPU_tanpa25.drop_duplicates(inplace=True)

# Libur

In [239]:
libur_raw = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/libur-nasional/dataset-libur-nasional-dan-weekend.csv')

In [240]:
libur_raw.head()

      tanggal  is_holiday_nasional      nama_libur  is_weekend  day_name
0  2010-01-01                    1  New Year's Day           0    Friday
1  2010-01-02                    0             NaN           1  Saturday
2  2010-01-03                    0             NaN           1    Sunday
3  2010-01-04                    0             NaN           0    Monday
4  2010-01-05                    0             NaN           0   Tuesday

In [241]:
libur_raw.isnull().sum()

tanggal                   0
is_holiday_nasional       0
nama_libur             5587
is_weekend                0
day_name                  0
dtype: int64

In [243]:
libur_raw.duplicated().sum()

np.int64(0)

In [246]:
libur_cleaned = libur_raw.drop(columns=['nama_libur'])
libur_cleaned = libur_cleaned.drop(columns=['day_name'])

In [247]:
libur_cleaned.head()

      tanggal  is_holiday_nasional  is_weekend
0  2010-01-01                    1           0
1  2010-01-02                    0           1
2  2010-01-03                    0           1
3  2010-01-04                    0           0
4  2010-01-05                    0           0

In [248]:
libur_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5844 entries, 0 to 5843
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tanggal              5844 non-null   object
 1   is_holiday_nasional  5844 non-null   int64
 2   is_weekend           5844 non-null   int64
dtypes: int64(2), object(1)
memory usage: 137.1+ KB

In [250]:
libur_cleaned['tanggal'] = pd.to_datetime(libur_cleaned['tanggal'])

# Join Tanggal ISPU

In [251]:
ISPU_joined = ISPU_tanpa25.merge(
    libur_cleaned,
    on='tanggal',
    how='left'
)

In [252]:
ISPU_joined.head()

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,kategori,kategori_enc,is_holiday_nasional,is_weekend
0,201001,2010-01-01,DKI1,60.0,4.0,73.0,27.0,14.0,73.0,co,SEDANG,1,1,0
1,201001,2010-01-02,DKI1,32.0,2.0,16.0,33.0,9.0,33.0,o3,BAIK,0,0,1
2,201001,2010-01-03,DKI1,27.0,2.0,19.0,20.0,9.0,27.0,pm10,BAIK,0,0,1
3,201001,2010-01-04,DKI1,22.0,2.0,16.0,15.0,6.0,22.0,pm10,BAIK,0,0,0
4,201001,2010-01-05,DKI1,25.0,2.0,17.0,15.0,8.0,25.0,pm10,BAIK,0,0,0

In [253]:
ISPU_joined.shape

(13507, 14)

In [254]:
ISPU_joined.isnull().sum()

periode_data           0
tanggal                0
stasiun                0
pm10                   0
so2                    0
co                     0
o3                     0
no2                    0
max                    0
critical               0
kategori               0
kategori_enc           0
is_holiday_nasional    0
is_weekend             0
dtype: int64

In [255]:
ISPU_joined['is_holiday_nasional'].unique()

array([1, 0])

In [258]:
ISPU_tanpa25['tanggal'].min(), ISPU_tanpa25['tanggal'].max()

(Timestamp('2010-01-01 00:00:00'), Timestamp('2025-08-31 00:00:00'))

In [259]:
libur_raw['tanggal'].min(), libur_raw['tanggal'].max()

(Timestamp('2010-01-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

# Cuaca

array(['DKI3 Jagakarsa', 'DKI1 Bunderan HI', 'DKI2 Kelapa Gading',
       'DKI4 Lubang Buaya', 'DKI1 Bundaran Hotel Indonesia (HI)',
       'DKI5 Kebon Jeruk Jakarta Barat', 'DKI5 Kebon Jeruk'], dtype=object)

In [269]:
cuaca1 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/cuaca-harian/cuaca-harian-dki1-bundaranhi.csv')

In [287]:
cuaca1

,time,temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),shortwave_radiation_sum (MJ/m²),temperature_2m_mean (°C),relative_humidity_2m_mean (%),...,relative_humidity_2m_min (%),cloud_cover_max (%),cloud_cover_min (%),wind_gusts_10m_mean (km/h),wind_speed_10m_mean (km/h),wind_gusts_10m_min (km/h),wind_speed_10m_min (km/h),surface_pressure_max (hPa),surface_pressure_min (hPa),stasiun
0,2010-01-01,29.4,24.4,4.0,14.0,16.0,246,16.24,26.6,81,...,69,100,99,21.0,10.5,11.9,6.9,1009.3,1005.1,DKI1
1,2010-01-02,30.8,24.0,6.5,4.0,14.7,238,19.80,26.9,82,...,69,100,91,16.5,7.7,9.0,4.4,1009.9,1006.0,DKI1
2,2010-01-03,30.4,24.3,7.6,11.0,12.6,244,17.32,26.7,83,...,70,100,81,18.4,9.4,11.9,6.5,1010.5,1006.5,DKI1
3,2010-01-04,30.3,25.4,0.9,5.0,19.3,239,20.43,27.4,81,...,70,100,17,23.8,13.5,14.4,9.6,1009.1,1005.1,DKI1
4,2010-01-05,29.9,24.8,14.3,7.0,15.9,247,15.86,26.4,83,...,72,100,99,21.6,11.1,10.4,7.8,1009.1,1006.0,DKI1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5717,2025-08-27,36.7,24.4,0.3,2.0,12.5,91,23.27,30.1,55,...,24,100,0,17.9,5.5,8.3,1.4,1012.1,1006.4,DKI1
5718,2025-08-28,34.5,24.3,9.5,11.0,12.7,268,19.46,28.9,63,...,39,100,9,19.7,5.8,8.6,0.0,1011.7,1007.7,DKI1
5719,2025-08-29,32.6,23.9,9.5,10.0,8.5,262,20.25,27.4,77,...,54,100,19,14.4,4.1,8.6,0.6,1012.7,1007.9,DKI1
5720,2025-08-30,31.8,24.5,7.1,10.0,10.3,145,20.17,27.2,77,...,54,100,33,16.5,5.3,6.8,0.5,1011.7,1007.5,DKI1
5721,2025-08-31,31.1,24.0,6.4,5.0,10.9,88,19.23,27.0,80,...,60,100,6,15.3,4.7,4.3,1.0,1011.6,1007.8,DKI1

In [271]:
cuaca1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5722 entries, 0 to 5721
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             5722 non-null   object
 1   temperature_2m_max (°C)          5722 non-null   float64
 2   temperature_2m_min (°C)          5722 non-null   float64
 3   precipitation_sum (mm)           5722 non-null   float64
 4   precipitation_hours (h)          5722 non-null   float64
 5   wind_speed_10m_max (km/h)        5722 non-null   float64
 6   wind_direction_10m_dominant (°)  5722 non-null   int64
 7   shortwave_radiation_sum (MJ/m²)  5722 non-null   float64
 8   temperature_2m_mean (°C)         5722 non-null   float64
 9   relative_humidity_2m_mean (%)    5722 non-null   int64
 10  cloud_cover_mean (%)             5722 non-null   int64
 11  surface_pressure_mean (hPa)      5722 non-null   float64
 12  wind_gusts_10m_max (km/h)        5722 non-null   float64
 13  winddirection_10m_dominant (°)   5722 non-null   int64
 14  relative_humidity_2m_max (%)     5722 non-null   int64
 15  relative_humidity_2m_min (%)     5722 non-null   int64
 16  cloud_cover_max (%)              5722 non-null   int64
 17  cloud_cover_min (%)              5722 non-null   int64
 18  wind_gusts_10m_mean (km/h)       5722 non-null   float64
 19  wind_speed_10m_mean (km/h)       5722 non-null   float64
 20  wind_gusts_10m_min (km/h)        5722 non-null   float64
 21  wind_speed_10m_min (km/h)        5722 non-null   float64
 22  surface_pressure_max (hPa)       5722 non-null   float64
 23  surface_pressure_min (hPa)       5722 non-null   float64
dtypes: float64(15), int64(8), object(1)
memory usage: 1.0+ MB

In [273]:
cuaca1['time'] = pd.to_datetime(cuaca1['time'])

In [285]:
cuaca1['stasiun'] = 'DKI1'

In [286]:
cuaca1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5722 entries, 0 to 5721
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             5722 non-null   datetime64[ns]
 1   temperature_2m_max (°C)          5722 non-null   float64
 2   temperature_2m_min (°C)          5722 non-null   float64
 3   precipitation_sum (mm)           5722 non-null   float64
 4   precipitation_hours (h)          5722 non-null   float64
 5   wind_speed_10m_max (km/h)        5722 non-null   float64
 6   wind_direction_10m_dominant (°)  5722 non-null   int64
 7   shortwave_radiation_sum (MJ/m²)  5722 non-null   float64
 8   temperature_2m_mean (°C)         5722 non-null   float64
 9   relative_humidity_2m_mean (%)    5722 non-null   int64
 10  cloud_cover_mean (%)             5722 non-null   int64
 11  surface_pressure_mean (hPa)      5722 non-null   float64
 12  wind_gusts_10m_max (km/h)        5722 non-null   float64
 13  winddirection_10m_dominant (°)   5722 non-null   int64
 14  relative_humidity_2m_max (%)     5722 non-null   int64
 15  relative_humidity_2m_min (%)     5722 non-null   int64
 16  cloud_cover_max (%)              5722 non-null   int64
 17  cloud_cover_min (%)              5722 non-null   int64
 18  wind_gusts_10m_mean (km/h)       5722 non-null   float64
 19  wind_speed_10m_mean (km/h)       5722 non-null   float64
 20  wind_gusts_10m_min (km/h)        5722 non-null   float64
 21  wind_speed_10m_min (km/h)        5722 non-null   float64
 22  surface_pressure_max (hPa)       5722 non-null   float64
 23  surface_pressure_min (hPa)       5722 non-null   float64
 24  stasiun                          5722 non-null   object
dtypes: datetime64[ns](1), float64(15), int64(8), object(1)
memory usage: 1.1+ MB

In [263]:
cuaca2 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/cuaca-harian/cuaca-harian-dki2-kelapagading.csv')

In [264]:
cuaca2

,time,temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),shortwave_radiation_sum (MJ/m²),temperature_2m_mean (°C),relative_humidity_2m_mean (%),...,relative_humidity_2m_max (%),relative_humidity_2m_min (%),cloud_cover_max (%),cloud_cover_min (%),wind_gusts_10m_mean (km/h),wind_speed_10m_mean (km/h),wind_gusts_10m_min (km/h),wind_speed_10m_min (km/h),surface_pressure_max (hPa),surface_pressure_min (hPa)
0,2010-01-01,29.4,24.6,5.2,10.0,16.5,255,16.85,26.7,81,...,89,69,100,99,21.1,10.6,11.9,7.4,1009.0,1004.9
1,2010-01-02,30.7,24.0,12.7,6.0,13.3,245,19.90,27.0,82,...,93,67,100,93,15.1,6.3,7.6,4.0,1009.7,1006.0
2,2010-01-03,30.6,24.3,10.2,8.0,11.0,252,19.53,26.8,83,...,91,69,100,72,17.3,8.4,10.4,5.6,1010.3,1006.2
3,2010-01-04,30.2,25.3,4.4,6.0,17.6,247,21.47,27.5,81,...,91,70,100,15,22.3,12.1,14.8,9.5,1008.8,1004.9
4,2010-01-05,29.9,24.9,14.2,10.0,15.5,256,16.82,26.5,83,...,89,72,100,99,20.9,10.2,13.0,6.8,1008.9,1005.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5717,2025-08-27,34.3,23.8,0.0,0.0,17.1,33,23.39,28.5,66,...,87,31,100,0,17.9,5.7,4.7,0.8,1011.9,1006.5
5718,2025-08-28,32.9,24.5,5.2,9.0,13.0,296,19.90,28.3,67,...,92,45,100,6,19.3,6.1,4.3,0.6,1011.4,1007.6
5719,2025-08-29,31.2,24.1,1.5,8.0,10.4,264,20.93,27.0,78,...,89,57,100,12,17.4,5.1,5.4,1.4,1012.5,1007.9
5720,2025-08-30,31.4,24.4,7.4,13.0,12.4,111,20.64,27.2,78,...,93,55,100,20,18.8,6.3,7.6,0.8,1011.5,1007.2
5721,2025-08-31,31.0,23.8,19.2,8.0,10.9,99,19.73,26.9,80,...,95,60,100,8,19.0,5.9,7.2,0.8,1011.5,1007.4

In [265]:
cuaca2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5722 entries, 0 to 5721
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             5722 non-null   object
 1   temperature_2m_max (°C)          5722 non-null   float64
 2   temperature_2m_min (°C)          5722 non-null   float64
 3   precipitation_sum (mm)           5722 non-null   float64
 4   precipitation_hours (h)          5722 non-null   float64
 5   wind_speed_10m_max (km/h)        5722 non-null   float64
 6   wind_direction_10m_dominant (°)  5722 non-null   int64
 7   shortwave_radiation_sum (MJ/m²)  5722 non-null   float64
 8   temperature_2m_mean (°C)         5722 non-null   float64
 9   relative_humidity_2m_mean (%)    5722 non-null   int64
 10  cloud_cover_mean (%)             5722 non-null   int64
 11  surface_pressure_mean (hPa)      5722 non-null   float64
 12  wind_gusts_10m_max (km/h)        5722 non-null   float64
 13  winddirection_10m_dominant (°)   5722 non-null   int64
 14  relative_humidity_2m_max (%)     5722 non-null   int64
 15  relative_humidity_2m_min (%)     5722 non-null   int64
 16  cloud_cover_max (%)              5722 non-null   int64
 17  cloud_cover_min (%)              5722 non-null   int64
 18  wind_gusts_10m_mean (km/h)       5722 non-null   float64
 19  wind_speed_10m_mean (km/h)       5722 non-null   float64
 20  wind_gusts_10m_min (km/h)        5722 non-null   float64
 21  wind_speed_10m_min (km/h)        5722 non-null   float64
 22  surface_pressure_max (hPa)       5722 non-null   float64
 23  surface_pressure_min (hPa)       5722 non-null   float64
dtypes: float64(15), int64(8), object(1)
memory usage: 1.0+ MB

In [275]:
cuaca2['time'] = pd.to_datetime(cuaca2['time'])

In [288]:
cuaca2['stasiun'] = 'DKI2'

In [276]:
cuaca3 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/cuaca-harian/cuaca-harian-dki3-jagakarsa.csv')

In [277]:
cuaca3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5722 entries, 0 to 5721
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             5722 non-null   object
 1   temperature_2m_max (°C)          5722 non-null   float64
 2   temperature_2m_min (°C)          5722 non-null   float64
 3   precipitation_sum (mm)           5722 non-null   float64
 4   precipitation_hours (h)          5722 non-null   float64
 5   wind_speed_10m_max (km/h)        5722 non-null   float64
 6   wind_direction_10m_dominant (°)  5722 non-null   int64
 7   shortwave_radiation_sum (MJ/m²)  5722 non-null   float64
 8   temperature_2m_mean (°C)         5722 non-null   float64
 9   relative_humidity_2m_mean (%)    5722 non-null   int64
 10  cloud_cover_mean (%)             5722 non-null   int64
 11  surface_pressure_mean (hPa)      5722 non-null   float64
 12  wind_gusts_10m_max (km/h)        5722 non-null   float64
 13  winddirection_10m_dominant (°)   5722 non-null   int64
 14  relative_humidity_2m_max (%)     5722 non-null   int64
 15  relative_humidity_2m_min (%)     5722 non-null   int64
 16  cloud_cover_max (%)              5722 non-null   int64
 17  cloud_cover_min (%)              5722 non-null   int64
 18  wind_gusts_10m_mean (km/h)       5722 non-null   float64
 19  wind_speed_10m_mean (km/h)       5722 non-null   float64
 20  wind_gusts_10m_min (km/h)        5722 non-null   float64
 21  wind_speed_10m_min (km/h)        5722 non-null   float64
 22  surface_pressure_max (hPa)       5722 non-null   float64
 23  surface_pressure_min (hPa)       5722 non-null   float64
dtypes: float64(15), int64(8), object(1)
memory usage: 1.0+ MB

In [278]:
cuaca3['time'] = pd.to_datetime(cuaca3['time'])

In [289]:
cuaca3['stasiun'] = 'DKI3'

In [279]:
cuaca4 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/cuaca-harian/cuaca-harian-dki4-lubangbuaya.csv')

In [280]:
cuaca4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5722 entries, 0 to 5721
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             5722 non-null   object
 1   temperature_2m_max (°C)          5722 non-null   float64
 2   temperature_2m_min (°C)          5722 non-null   float64
 3   precipitation_sum (mm)           5722 non-null   float64
 4   precipitation_hours (h)          5722 non-null   float64
 5   wind_speed_10m_max (km/h)        5722 non-null   float64
 6   wind_direction_10m_dominant (°)  5722 non-null   int64
 7   shortwave_radiation_sum (MJ/m²)  5722 non-null   float64
 8   temperature_2m_mean (°C)         5722 non-null   float64
 9   relative_humidity_2m_mean (%)    5722 non-null   int64
 10  cloud_cover_mean (%)             5722 non-null   int64
 11  surface_pressure_mean (hPa)      5722 non-null   float64
 12  wind_gusts_10m_max (km/h)        5722 non-null   float64
 13  winddirection_10m_dominant (°)   5722 non-null   int64
 14  relative_humidity_2m_max (%)     5722 non-null   int64
 15  relative_humidity_2m_min (%)     5722 non-null   int64
 16  cloud_cover_max (%)              5722 non-null   int64
 17  cloud_cover_min (%)              5722 non-null   int64
 18  wind_gusts_10m_mean (km/h)       5722 non-null   float64
 19  wind_speed_10m_mean (km/h)       5722 non-null   float64
 20  wind_gusts_10m_min (km/h)        5722 non-null   float64
 21  wind_speed_10m_min (km/h)        5722 non-null   float64
 22  surface_pressure_max (hPa)       5722 non-null   float64
 23  surface_pressure_min (hPa)       5722 non-null   float64
dtypes: float64(15), int64(8), object(1)
memory usage: 1.0+ MB

In [290]:
cuaca4['stasiun'] = 'DKI4'

In [281]:
cuaca5 = pd.read_csv('/content/drive/MyDrive/DATASET/penyisihan-datavidia-10/cuaca-harian/cuaca-harian-dki5-kebonjeruk.csv')

In [282]:
cuaca5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5722 entries, 0 to 5721
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             5722 non-null   object
 1   temperature_2m_max (°C)          5722 non-null   float64
 2   temperature_2m_min (°C)          5722 non-null   float64
 3   precipitation_sum (mm)           5722 non-null   float64
 4   precipitation_hours (h)          5722 non-null   float64
 5   wind_speed_10m_max (km/h)        5722 non-null   float64
 6   wind_direction_10m_dominant (°)  5722 non-null   int64
 7   shortwave_radiation_sum (MJ/m²)  5722 non-null   float64
 8   temperature_2m_mean (°C)         5722 non-null   float64
 9   relative_humidity_2m_mean (%)    5722 non-null   int64
 10  cloud_cover_mean (%)             5722 non-null   int64
 11  surface_pressure_mean (hPa)      5722 non-null   float64
 12  wind_gusts_10m_max (km/h)        5722 non-null   float64
 13  winddirection_10m_dominant (°)   5722 non-null   int64
 14  relative_humidity_2m_max (%)     5722 non-null   int64
 15  relative_humidity_2m_min (%)     5722 non-null   int64
 16  cloud_cover_max (%)              5722 non-null   int64
 17  cloud_cover_min (%)              5722 non-null   int64
 18  wind_gusts_10m_mean (km/h)       5722 non-null   float64
 19  wind_speed_10m_mean (km/h)       5722 non-null   float64
 20  wind_gusts_10m_min (km/h)        5722 non-null   float64
 21  wind_speed_10m_min (km/h)        5722 non-null   float64
 22  surface_pressure_max (hPa)       5722 non-null   float64
 23  surface_pressure_min (hPa)       5722 non-null   float64
dtypes: float64(15), int64(8), object(1)
memory usage: 1.0+ MB

In [283]:
cuaca5['time']= pd.to_datetime(cuaca5['time'])

In [291]:
cuaca5['stasiun'] = 'DKI5'

In [292]:
cuaca_all = pd.concat(
    [cuaca1, cuaca2, cuaca3, cuaca4, cuaca5],
    ignore_index=True
)

In [294]:
cuaca_all[['time', 'stasiun']].duplicated().sum()

np.int64(0)

In [295]:
cuaca_all.rename(columns={'time': 'tanggal'}, inplace=True)

In [296]:
cuaca_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28610 entries, 0 to 28609
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   tanggal                          28610 non-null  object
 1   temperature_2m_max (°C)          28610 non-null  float64
 2   temperature_2m_min (°C)          28610 non-null  float64
 3   precipitation_sum (mm)           28610 non-null  float64
 4   precipitation_hours (h)          28610 non-null  float64
 5   wind_speed_10m_max (km/h)        28610 non-null  float64
 6   wind_direction_10m_dominant (°)  28610 non-null  int64
 7   shortwave_radiation_sum (MJ/m²)  28610 non-null  float64
 8   temperature_2m_mean (°C)         28610 non-null  float64
 9   relative_humidity_2m_mean (%)    28610 non-null  int64
 10  cloud_cover_mean (%)             28610 non-null  int64
 11  surface_pressure_mean (hPa)      28610 non-null  float64
 12  wind_gusts_10m_max (km/h)        28610 non-null  float64
 13  winddirection_10m_dominant (°)   28610 non-null  int64
 14  relative_humidity_2m_max (%)     28610 non-null  int64
 15  relative_humidity_2m_min (%)     28610 non-null  int64
 16  cloud_cover_max (%)              28610 non-null  int64
 17  cloud_cover_min (%)              28610 non-null  int64
 18  wind_gusts_10m_mean (km/h)       28610 non-null  float64
 19  wind_speed_10m_mean (km/h)       28610 non-null  float64
 20  wind_gusts_10m_min (km/h)        28610 non-null  float64
 21  wind_speed_10m_min (km/h)        28610 non-null  float64
 22  surface_pressure_max (hPa)       28610 non-null  float64
 23  surface_pressure_min (hPa)       28610 non-null  float64
 24  stasiun                          28610 non-null  object
dtypes: float64(15), int64(8), object(2)
memory usage: 5.5+ MB

In [297]:
cuaca_all['tanggal'] = pd.to_datetime(cuaca_all['tanggal'])

In [298]:
cuaca_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28610 entries, 0 to 28609
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   tanggal                          28610 non-null  datetime64[ns]
 1   temperature_2m_max (°C)          28610 non-null  float64
 2   temperature_2m_min (°C)          28610 non-null  float64
 3   precipitation_sum (mm)           28610 non-null  float64
 4   precipitation_hours (h)          28610 non-null  float64
 5   wind_speed_10m_max (km/h)        28610 non-null  float64
 6   wind_direction_10m_dominant (°)  28610 non-null  int64
 7   shortwave_radiation_sum (MJ/m²)  28610 non-null  float64
 8   temperature_2m_mean (°C)         28610 non-null  float64
 9   relative_humidity_2m_mean (%)    28610 non-null  int64
 10  cloud_cover_mean (%)             28610 non-null  int64
 11  surface_pressure_mean (hPa)      28610 non-null  float64
 12  wind_gusts_10m_max (km/h)        28610 non-null  float64
 13  winddirection_10m_dominant (°)   28610 non-null  int64
 14  relative_humidity_2m_max (%)     28610 non-null  int64
 15  relative_humidity_2m_min (%)     28610 non-null  int64
 16  cloud_cover_max (%)              28610 non-null  int64
 17  cloud_cover_min (%)              28610 non-null  int64
 18  wind_gusts_10m_mean (km/h)       28610 non-null  float64
 19  wind_speed_10m_mean (km/h)       28610 non-null  float64
 20  wind_gusts_10m_min (km/h)        28610 non-null  float64
 21  wind_speed_10m_min (km/h)        28610 non-null  float64
 22  surface_pressure_max (hPa)       28610 non-null  float64
 23  surface_pressure_min (hPa)       28610 non-null  float64
 24  stasiun                          28610 non-null  object
dtypes: datetime64[ns](1), float64(15), int64(8), object(1)
memory usage: 5.5+ MB

# Join ISPU_joined dengan Cuaca per lokasi

In [301]:
cuaca_cols = [
    'temperature_2m_mean (°C)',
    'precipitation_sum (mm)',
    'wind_speed_10m_mean (km/h)',
    'relative_humidity_2m_mean (%)',
    'cloud_cover_mean (%)',
    'surface_pressure_mean (hPa)',
    'shortwave_radiation_sum (MJ/m²)'
]


ISPU_final = ISPU_joined.merge(
    cuaca_all[['tanggal', 'stasiun'] + cuaca_cols],
    on=['tanggal', 'stasiun'],
    how='left'
)

In [302]:
ISPU_final.head()

,periode_data,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,...,kategori_enc,is_holiday_nasional,is_weekend,temperature_2m_mean (°C),precipitation_sum (mm),wind_speed_10m_mean (km/h),relative_humidity_2m_mean (%),cloud_cover_mean (%),surface_pressure_mean (hPa),shortwave_radiation_sum (MJ/m²)
0,201001,2010-01-01,DKI1,60.0,4.0,73.0,27.0,14.0,73.0,co,...,1,1,0,26.6,4.0,10.5,81,100,1007.5,16.24
1,201001,2010-01-02,DKI1,32.0,2.0,16.0,33.0,9.0,33.0,o3,...,0,0,1,26.9,6.5,7.7,82,99,1008.1,19.80
2,201001,2010-01-03,DKI1,27.0,2.0,19.0,20.0,9.0,27.0,pm10,...,0,0,1,26.7,7.6,9.4,83,97,1008.5,17.32
3,201001,2010-01-04,DKI1,22.0,2.0,16.0,15.0,6.0,22.0,pm10,...,0,0,0,27.4,0.9,13.5,81,69,1007.5,20.43
4,201001,2010-01-05,DKI1,25.0,2.0,17.0,15.0,8.0,25.0,pm10,...,0,0,0,26.4,14.3,11.1,83,100,1007.7,15.86

In [303]:
ISPU_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13507 entries, 0 to 13506
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   periode_data                     13507 non-null  int64
 1   tanggal                          13507 non-null  datetime64[ns]
 2   stasiun                          13507 non-null  object
 3   pm10                             13507 non-null  float64
 4   so2                              13507 non-null  float64
 5   co                               13507 non-null  float64
 6   o3                               13507 non-null  float64
 7   no2                              13507 non-null  float64
 8   max                              13507 non-null  float64
 9   critical                         13507 non-null  object
 10  kategori                         13507 non-null  category
 11  kategori_enc                     13507 non-null  category
 12  is_holiday_nasional              13507 non-null  int64
 13  is_weekend                       13507 non-null  int64
 14  temperature_2m_mean (°C)         13507 non-null  float64
 15  precipitation_sum (mm)           13507 non-null  float64
 16  wind_speed_10m_mean (km/h)       13507 non-null  float64
 17  relative_humidity_2m_mean (%)    13507 non-null  int64
 18  cloud_cover_mean (%)             13507 non-null  int64
 19  surface_pressure_mean (hPa)      13507 non-null  float64
 20  shortwave_radiation_sum (MJ/m²)  13507 non-null  float64
dtypes: category(2), datetime64[ns](1), float64(11), int64(5), object(2)
memory usage: 2.0+ MB

In [304]:
ISPU_final.rename(columns={
    'temperature_2m_mean (°C)': 'temp_mean',
    'precipitation_sum (mm)': 'rain_sum',
    'wind_speed_10m_mean (km/h)': 'wind_mean',
    'relative_humidity_2m_mean (%)': 'humidity_mean',
    'cloud_cover_mean (%)': 'cloud_mean',
    'surface_pressure_mean (hPa)': 'pressure_mean',
    'shortwave_radiation_sum (MJ/m²)': 'radiation_sum'
}, inplace=True)

In [305]:
ISPU_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13507 entries, 0 to 13506
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   periode_data         13507 non-null  int64
 1   tanggal              13507 non-null  datetime64[ns]
 2   stasiun              13507 non-null  object
 3   pm10                 13507 non-null  float64
 4   so2                  13507 non-null  float64
 5   co                   13507 non-null  float64
 6   o3                   13507 non-null  float64
 7   no2                  13507 non-null  float64
 8   max                  13507 non-null  float64
 9   critical             13507 non-null  object
 10  kategori             13507 non-null  category
 11  kategori_enc         13507 non-null  category
 12  is_holiday_nasional  13507 non-null  int64
 13  is_weekend           13507 non-null  int64
 14  temp_mean            13507 non-null  float64
 15  rain_sum             13507 non-null  float64
 16  wind_mean            13507 non-null  float64
 17  humidity_mean        13507 non-null  int64
 18  cloud_mean           13507 non-null  int64
 19  pressure_mean        13507 non-null  float64
 20  radiation_sum        13507 non-null  float64
dtypes: category(2), datetime64[ns](1), float64(11), int64(5), object(2)
memory usage: 2.0+ MB

# Pemodelan

In [345]:
df = ISPU_final.copy()
# num_features = [
#     'temp_mean',
#     'rain_sum',
#     'wind_mean',
#     'humidity_mean',
#     'cloud_mean',
#     'pressure_mean',
#     'radiation_sum'
# ]

df['bulan'] = df['tanggal'].dt.month
df['hari'] = df['tanggal'].dt.day
df['hari_dalam_minggu'] = df['tanggal'].dt.weekday
time_features = [
    'bulan',
    'hari',
    'hari_dalam_minggu'
]

calendar_features = [
    'is_weekend',
    'is_holiday_nasional'
]

cat_features = ['stasiun']

features = (
    # num_features +
    time_features +
    calendar_features +
    cat_features
)

In [346]:
X = df[features]
y = df['kategori']

In [347]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_enc = le.fit_transform(y)

In [367]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13507 entries, 0 to 13506
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   periode_data         13507 non-null  int64
 1   tanggal              13507 non-null  datetime64[ns]
 2   stasiun              13507 non-null  object
 3   pm10                 13507 non-null  float64
 4   so2                  13507 non-null  float64
 5   co                   13507 non-null  float64
 6   o3                   13507 non-null  float64
 7   no2                  13507 non-null  float64
 8   max                  13507 non-null  float64
 9   critical             13507 non-null  object
 10  kategori             13507 non-null  category
 11  kategori_enc         13507 non-null  category
 12  is_holiday_nasional  13507 non-null  int64
 13  is_weekend           13507 non-null  int64
 14  temp_mean            13507 non-null  float64
 15  rain_sum             13507 non-null  float64
 16  wind_mean            13507 non-null  float64
 17  humidity_mean        13507 non-null  int64
 18  cloud_mean           13507 non-null  int64
 19  pressure_mean        13507 non-null  float64
 20  radiation_sum        13507 non-null  float64
 21  bulan                13507 non-null  int32
 22  hari                 13507 non-null  int32
 23  hari_dalam_minggu    13507 non-null  int32
dtypes: category(2), datetime64[ns](1), float64(11), int32(3), int64(5), object(2)
memory usage: 2.1+ MB

In [348]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc,
    test_size=0.2,
    shuffle=False
)

In [319]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.8)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.2)

In [349]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=600,
    learning_rate=0.05,
    depth=6,
    loss_function='MultiClass',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=100
)

model.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_test, y_test),
    use_best_model=True
)

0:	learn: 0.6748727	test: 0.7746114	best: 0.7746114 (0)	total: 40.9ms	remaining: 24.5s
100:	learn: 0.6807034	test: 0.7786825	best: 0.7794226 (55)	total: 3.19s	remaining: 15.8s
200:	learn: 0.6847756	test: 0.7779423	best: 0.7794226 (55)	total: 7.65s	remaining: 15.2s
300:	learn: 0.6887552	test: 0.7749815	best: 0.7794226 (55)	total: 10.8s	remaining: 10.7s
400:	learn: 0.6918093	test: 0.7712805	best: 0.7794226 (55)	total: 14.1s	remaining: 6.97s
500:	learn: 0.6943082	test: 0.7698001	best: 0.7794226 (55)	total: 17.4s	remaining: 3.43s
599:	learn: 0.6962517	test: 0.7694301	best: 0.7794226 (55)	total: 22.2s	remaining: 0us

bestTest = 0.7794226499
bestIteration = 55

Shrink model to first 56 iterations.

In [350]:
import joblib

model.save_model('model_ispu_final.cbm')
joblib.dump(le, 'label_encoder.pkl')

['label_encoder.pkl']

# Data UJI/SUBMITION

In [357]:
tanggal_sub = pd.date_range(
    start='2025-09-01',
    end='2025-11-30',
    freq='D'
)

stasiun_list = ['DKI1', 'DKI2', 'DKI3', 'DKI4', 'DKI5']

df_sub = pd.MultiIndex.from_product(
    [tanggal_sub, stasiun_list],
    names=['tanggal', 'stasiun']
).to_frame(index=False)

In [358]:
df_sub

       tanggal stasiun
0   2025-09-01    DKI1
1   2025-09-01    DKI2
2   2025-09-01    DKI3
3   2025-09-01    DKI4
4   2025-09-01    DKI5
..         ...     ...
450 2025-11-30    DKI1
451 2025-11-30    DKI2
452 2025-11-30    DKI3
453 2025-11-30    DKI4
454 2025-11-30    DKI5

[455 rows x 2 columns]

In [359]:
df_sub['bulan'] = df_sub['tanggal'].dt.month
df_sub['hari'] = df_sub['tanggal'].dt.day
df_sub['hari_dalam_minggu'] = df_sub['tanggal'].dt.weekday
df_sub['is_weekend'] = (df_sub['hari_dalam_minggu'] >= 5).astype(int)

In [360]:
df_sub = df_sub.merge(
    libur_cleaned[['tanggal', 'is_holiday_nasional']],
    on='tanggal',
    how='left'
)

df_sub['is_holiday_nasional'] = df_sub['is_holiday_nasional'].fillna(0)

In [355]:
# df_sub = df_sub.merge(
#     cuaca_all,
#     on=['tanggal', 'stasiun'],
#     how='left'
# )

In [361]:
df_sub

,tanggal,stasiun,bulan,hari,hari_dalam_minggu,is_weekend,is_holiday_nasional
0,2025-09-01,DKI1,9,1,0,0,0
1,2025-09-01,DKI2,9,1,0,0,0
2,2025-09-01,DKI3,9,1,0,0,0
3,2025-09-01,DKI4,9,1,0,0,0
4,2025-09-01,DKI5,9,1,0,0,0
...,...,...,...,...,...,...,...
450,2025-11-30,DKI1,11,30,6,1,0
451,2025-11-30,DKI2,11,30,6,1,0
452,2025-11-30,DKI3,11,30,6,1,0
453,2025-11-30,DKI4,11,30,6,1,0
454,2025-11-30,DKI5,11,30,6,1,0

In [339]:
# df_sub.rename(columns={
#     'temperature_2m_mean (°C)': 'temp_mean',
#     'precipitation_sum (mm)': 'rain_sum',
#     'wind_speed_10m_mean (km/h)': 'wind_mean',
#     'relative_humidity_2m_mean (%)': 'humidity_mean',
#     'cloud_cover_mean (%)': 'cloud_mean',
#     'surface_pressure_mean (hPa)': 'pressure_mean',
#     'shortwave_radiation_sum (MJ/m²)': 'radiation_sum'
# }, inplace=True)

In [378]:
features = [
    'bulan',
    'hari',

    'stasiun',

    'hari_dalam_minggu',
    'is_weekend',
    'is_holiday_nasional'
]

X_sub = df_sub[features]

In [379]:
cat_features = ['stasiun']

In [376]:
from catboost import Pool

In [384]:
X_sub = X_sub[features]

X_sub_pool = Pool(
    X_sub,
    cat_features=['stasiun']
)

y_pred = model.predict(X_sub_pool)

# Tambahkan .ravel() setelah .astype(int)
df_sub['kategori'] = le.inverse_transform(y_pred.astype(int).ravel())

In [385]:
df_sub['kategori'].value_counts()

kategori
SEDANG    455
Name: count, dtype: int64

In [386]:
pd.crosstab(df_sub['stasiun'], df_sub['kategori'])

kategori  SEDANG
stasiun
DKI1          91
DKI2          91
DKI3          91
DKI4          91
DKI5          91

In [387]:
df_sub['tanggal'].min(), df_sub['tanggal'].max()

(Timestamp('2025-09-01 00:00:00'), Timestamp('2025-11-30 00:00:00'))

In [388]:
df_submit = df_sub[['tanggal', 'stasiun', 'kategori']]

In [389]:
df_submit['id'] = (
    df_submit['tanggal'].dt.strftime('%Y-%m-%d')
    + '_' +
    df_submit['stasiun'].astype(str)
)

/tmp/ipython-input-1645323735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_submit['id'] = (

In [391]:
df_submit.drop(columns=['tanggal', 'stasiun'], inplace=True)

/tmp/ipython-input-776087094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_submit.drop(columns=['tanggal', 'stasiun'], inplace=True)

In [393]:
# Misal urutan awal acak, kita ingin urutan: id, lalu kategori
df_submit = df_submit[['id', 'kategori']]

In [394]:
df_submit

                  id kategori
0    2025-09-01_DKI1   SEDANG
1    2025-09-01_DKI2   SEDANG
2    2025-09-01_DKI3   SEDANG
3    2025-09-01_DKI4   SEDANG
4    2025-09-01_DKI5   SEDANG
..               ...      ...
450  2025-11-30_DKI1   SEDANG
451  2025-11-30_DKI2   SEDANG
452  2025-11-30_DKI3   SEDANG
453  2025-11-30_DKI4   SEDANG
454  2025-11-30_DKI5   SEDANG

[455 rows x 2 columns]

In [395]:
df_submit.to_csv(
    'submission.csv',
    index=False
)