<a href="https://colab.research.google.com/github/Leonanda1013/DataLoverz/blob/main/Competition/Playground/Playground_s6e1_StudentTestScore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [213]:
import pandas as pd
import numpy as np

In [214]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [215]:
df = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e1/train.csv')

In [216]:
dfTest = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e1/test.csv')

In [217]:
df.head(
)

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [218]:
df = df.set_index('id')

In [219]:
dfTest = dfTest.set_index('id')

In [220]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 630000 entries, 0 to 629999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               630000 non-null  int64
 1   gender            630000 non-null  object
 2   course            630000 non-null  object
 3   study_hours       630000 non-null  float64
 4   class_attendance  630000 non-null  float64
 5   internet_access   630000 non-null  object
 6   sleep_hours       630000 non-null  float64
 7   sleep_quality     630000 non-null  object
 8   study_method      630000 non-null  object
 9   facility_rating   630000 non-null  object
 10  exam_difficulty   630000 non-null  object
 11  exam_score        630000 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 62.5+ MB

In [221]:
df['gender'].value_counts()

gender
other     211097
male      210593
female    208310
Name: count, dtype: int64

In [222]:
for col in dfTest.columns:
    print(dfTest[col].value_counts())
    print()

age
21    37184
23    35488
20    34507
19    33556
24    32902
18    32496
22    32362
17    31505
Name: count, dtype: int64

gender
male      90682
other     90111
female    89207
Name: count, dtype: int64

course
b.tech     56461
b.sc       47712
b.com      47335
bca        38089
bba        32099
ba         26874
diploma    21430
Name: count, dtype: int64

study_hours
0.080    6123
7.910    5340
4.690    1022
4.670     986
4.010     865
         ...
5.160      61
1.840      57
6.520      40
0.372       1
6.077       1
Name: count, Length: 786, dtype: int64

class_attendance
99.40    6502
40.60    2871
89.40     899
97.30     896
97.70     877
         ...
96.44       1
94.65       1
84.91       1
61.27       1
64.79       1
Name: count, Length: 604, dtype: int64

internet_access
yes    248671
no      21329
Name: count, dtype: int64

sleep_hours
9.90    8147
4.10    7688
9.20    5601
6.20    5389
9.70    5343
        ...
4.11       1
4.44       1
4.81       1
4.37       1
4.55       1
Name: count, Length: 64, dtype: int64

sleep_quality
good       91754
poor       91680
average    86566
Name: count, dtype: int64

study_method
coaching         56698
self-study       55941
group study      52780
mixed            52692
online videos    51889
Name: count, dtype: int64

facility_rating
medium    91816
low       91322
high      86862
Name: count, dtype: int64

exam_difficulty
moderate    151656
easy         75631
hard         42713
Name: count, dtype: int64

In [223]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dfTest['gender'] = le.fit_transform(dfTest['gender'])

In [224]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [225]:
df['gender'].value_counts()

gender
2    211097
1    210593
0    208310
Name: count, dtype: int64

In [226]:
dfTest = pd.get_dummies(dfTest, columns=['course'])

In [227]:
df = pd.get_dummies(df, columns=['course'])

In [228]:
df['internet_access'].value_counts()

internet_access
yes    579423
no      50577
Name: count, dtype: int64

In [229]:
dfTest['internet_access'] = le.fit_transform(dfTest['internet_access'])

In [230]:
df['internet_access'] = le.fit_transform(df['internet_access'])

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 630000 entries, 0 to 629999
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               630000 non-null  int64
 1   gender            630000 non-null  int64
 2   study_hours       630000 non-null  float64
 3   class_attendance  630000 non-null  float64
 4   internet_access   630000 non-null  int64
 5   sleep_hours       630000 non-null  float64
 6   sleep_quality     630000 non-null  object
 7   study_method      630000 non-null  object
 8   facility_rating   630000 non-null  object
 9   exam_difficulty   630000 non-null  object
 10  exam_score        630000 non-null  float64
 11  course_b.com      630000 non-null  bool
 12  course_b.sc       630000 non-null  bool
 13  course_b.tech     630000 non-null  bool
 14  course_ba         630000 non-null  bool
 15  course_bba        630000 non-null  bool
 16  course_bca        630000 non-null  bool
 17  course_diploma    630000 non-null  bool
dtypes: bool(7), float64(4), int64(3), object(4)
memory usage: 61.9+ MB

In [232]:
dfTest['sleep_quality'].value_counts()

sleep_quality
good       91754
poor       91680
average    86566
Name: count, dtype: int64

In [233]:
mappingSleep = {
    'poor': 0,
    'average': 1,
    'good': 2,
}
df['sleep_quality'] = df['sleep_quality'].map(mappingSleep)
dfTest['sleep_quality'] = dfTest['sleep_quality'].map(mappingSleep)

In [234]:
dfTest['study_method'].value_counts()

study_method
coaching         56698
self-study       55941
group study      52780
mixed            52692
online videos    51889
Name: count, dtype: int64

In [235]:
dfTest = pd.get_dummies(dfTest, columns=['study_method'])
df = pd.get_dummies(df, columns=['study_method'])

In [236]:
df['facility_rating'].value_counts()

facility_rating
medium    214082
low       212378
high      203540
Name: count, dtype: int64

In [237]:
mappingRating = {
    'low': 0,
    'medium': 1,
    'high': 2,
}

df['facility_rating'] = df['facility_rating'].map(mappingRating)
dfTest['facility_rating'] = dfTest['facility_rating'].map(mappingRating)

In [238]:
df['exam_difficulty'].value_counts(

)

exam_difficulty
moderate    353982
easy        176540
hard         99478
Name: count, dtype: int64

In [239]:
mappingExam = {
    'easy': 0,
    'moderate': 1,
    'hard': 2,
}

df['exam_difficulty'] = df['exam_difficulty'].map(mappingExam)
dfTest['exam_difficulty'] = dfTest['exam_difficulty'].map(mappingExam)

In [241]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 630000 entries, 0 to 629999
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   age                         630000 non-null  int64
 1   gender                      630000 non-null  int64
 2   study_hours                 630000 non-null  float64
 3   class_attendance            630000 non-null  float64
 4   internet_access             630000 non-null  int64
 5   sleep_hours                 630000 non-null  float64
 6   sleep_quality               630000 non-null  int64
 7   facility_rating             630000 non-null  int64
 8   exam_difficulty             630000 non-null  int64
 9   exam_score                  630000 non-null  float64
 10  course_b.com                630000 non-null  bool
 11  course_b.sc                 630000 non-null  bool
 12  course_b.tech               630000 non-null  bool
 13  course_ba                   630000 non-null  bool
 14  course_bba                  630000 non-null  bool
 15  course_bca                  630000 non-null  bool
 16  course_diploma              630000 non-null  bool
 17  study_method_coaching       630000 non-null  bool
 18  study_method_group study    630000 non-null  bool
 19  study_method_mixed          630000 non-null  bool
 20  study_method_online videos  630000 non-null  bool
 21  study_method_self-study     630000 non-null  bool
dtypes: bool(12), float64(4), int64(6)
memory usage: 60.1 MB

In [242]:
bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols] = df[bool_cols].astype(int)
bool_cols = dfTest.select_dtypes(include='bool').columns

dfTest[bool_cols] = dfTest[bool_cols].astype(int)

In [243]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 630000 entries, 0 to 629999
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   age                         630000 non-null  int64
 1   gender                      630000 non-null  int64
 2   study_hours                 630000 non-null  float64
 3   class_attendance            630000 non-null  float64
 4   internet_access             630000 non-null  int64
 5   sleep_hours                 630000 non-null  float64
 6   sleep_quality               630000 non-null  int64
 7   facility_rating             630000 non-null  int64
 8   exam_difficulty             630000 non-null  int64
 9   exam_score                  630000 non-null  float64
 10  course_b.com                630000 non-null  int64
 11  course_b.sc                 630000 non-null  int64
 12  course_b.tech               630000 non-null  int64
 13  course_ba                   630000 non-null  int64
 14  course_bba                  630000 non-null  int64
 15  course_bca                  630000 non-null  int64
 16  course_diploma              630000 non-null  int64
 17  study_method_coaching       630000 non-null  int64
 18  study_method_group study    630000 non-null  int64
 19  study_method_mixed          630000 non-null  int64
 20  study_method_online videos  630000 non-null  int64
 21  study_method_self-study     630000 non-null  int64
dtypes: float64(4), int64(18)
memory usage: 110.5 MB

In [244]:
dfTest.info()

<class 'pandas.core.frame.DataFrame'>
Index: 270000 entries, 630000 to 899999
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   age                         270000 non-null  int64
 1   gender                      270000 non-null  int64
 2   study_hours                 270000 non-null  float64
 3   class_attendance            270000 non-null  float64
 4   internet_access             270000 non-null  int64
 5   sleep_hours                 270000 non-null  float64
 6   sleep_quality               270000 non-null  int64
 7   facility_rating             270000 non-null  int64
 8   exam_difficulty             270000 non-null  int64
 9   course_b.com                270000 non-null  int64
 10  course_b.sc                 270000 non-null  int64
 11  course_b.tech               270000 non-null  int64
 12  course_ba                   270000 non-null  int64
 13  course_bba                  270000 non-null  int64
 14  course_bca                  270000 non-null  int64
 15  course_diploma              270000 non-null  int64
 16  study_method_coaching       270000 non-null  int64
 17  study_method_group study    270000 non-null  int64
 18  study_method_mixed          270000 non-null  int64
 19  study_method_online videos  270000 non-null  int64
 20  study_method_self-study     270000 non-null  int64
dtypes: float64(3), int64(18)
memory usage: 45.3 MB

In [245]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X = df.drop(columns='exam_score')
y = df['exam_score']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
print(mae)

7.00002448698522

In [246]:
pred = model.predict(dfTest)

In [247]:
pred

array([71.334595, 71.03483 , 88.39886 , ..., 90.094925, 53.780502,
       68.05787 ], dtype=float32)

In [248]:
dfTest['exam_score_pred'] = pred

In [249]:
dfTest

,age,gender,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,facility_rating,exam_difficulty,course_b.com,...,course_ba,course_bba,course_bca,course_diploma,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,exam_score_pred
id,,,,,,,,,,,,,,,,,,,,,
630000,24,2,6.85,65.2,1,5.2,0,2,0,0,...,1,0,0,0,0,1,0,0,0,71.334595
630001,18,1,6.61,45.0,0,9.3,0,0,0,0,...,0,0,0,1,1,0,0,0,0,71.034828
630002,24,0,6.60,98.5,1,6.2,2,1,1,0,...,0,0,0,0,0,1,0,0,0,88.398857
630003,24,1,3.03,66.3,1,5.7,1,1,1,0,...,0,0,0,1,0,0,1,0,0,55.586254
630004,20,0,2.03,42.4,1,9.2,1,0,1,0,...,0,0,0,0,1,0,0,0,0,47.273746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,21,2,2.55,82.3,1,8.4,1,1,2,1,...,0,0,0,0,0,0,1,0,0,60.750401
899996,17,0,0.49,46.4,1,8.8,2,0,0,1,...,0,0,0,0,0,0,1,0,0,40.469288
899997,22,1,6.62,74.7,1,5.5,2,2,0,0,...,0,1,0,0,1,0,0,0,0,90.094925
899998,22,2,4.08,51.8,1,8.7,0,2,1,0,...,1,0,0,0,0,0,0,1,0,53.780502
899999,20,0,5.86,59.7,1,8.9,0,1,1,1,...,0,0,0,0,0,0,1,0,0,68.057869

In [250]:
dfTest = dfTest.reset_index()

In [255]:
dfSubmit = dfTest[['id','exam_score_pred']]

In [252]:
dfTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          270000 non-null  int64
 1   age                         270000 non-null  int64
 2   gender                      270000 non-null  int64
 3   study_hours                 270000 non-null  float64
 4   class_attendance            270000 non-null  float64
 5   internet_access             270000 non-null  int64
 6   sleep_hours                 270000 non-null  float64
 7   sleep_quality               270000 non-null  int64
 8   facility_rating             270000 non-null  int64
 9   exam_difficulty             270000 non-null  int64
 10  course_b.com                270000 non-null  int64
 11  course_b.sc                 270000 non-null  int64
 12  course_b.tech               270000 non-null  int64
 13  course_ba                   270000 non-null  int64
 14  course_bba                  270000 non-null  int64
 15  course_bca                  270000 non-null  int64
 16  course_diploma              270000 non-null  int64
 17  study_method_coaching       270000 non-null  int64
 18  study_method_group study    270000 non-null  int64
 19  study_method_mixed          270000 non-null  int64
 20  study_method_online videos  270000 non-null  int64
 21  study_method_self-study     270000 non-null  int64
 22  exam_score_pred             270000 non-null  float32
dtypes: float32(1), float64(3), int64(19)
memory usage: 46.3 MB

In [ ]:
dfTest

In [260]:
dfSubmit = dfSubmit.rename(columns={'exam_score_pred': 'exam_score'})

In [261]:
dfSubmit

            id  exam_score
0       630000   71.334595
1       630001   71.034828
2       630002   88.398857
3       630003   55.586254
4       630004   47.273746
...        ...         ...
269995  899995   60.750401
269996  899996   40.469288
269997  899997   90.094925
269998  899998   53.780502
269999  899999   68.057869

[270000 rows x 2 columns]

In [258]:
dfSubmit.set_index('id')

        exam_score_pred
id
630000        71.334595
630001        71.034828
630002        88.398857
630003        55.586254
630004        47.273746
...                 ...
899995        60.750401
899996        40.469288
899997        90.094925
899998        53.780502
899999        68.057869

[270000 rows x 1 columns]

In [262]:
dfSubmit.to_csv('submission.csv', index=False)