<a href="https://colab.research.google.com/github/Leonanda1013/DataLoverz/blob/main/Competition/Playground/Playground_s6e4_IrrigationNeed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
df_train = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e4/train.csv')

In [22]:
df_train.head()

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low

In [23]:
df_train.tail()

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
629995,629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,...,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,Medium
629996,629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,...,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,Medium
629997,629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,...,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,High
629998,629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,...,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,Low
629999,629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,...,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,Low

In [24]:
df_train

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,...,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,Medium
629996,629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,...,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,Medium
629997,629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,...,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,High
629998,629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,...,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,Low
629999,629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,...,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,Low

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       630000 non-null  int64
 1   Soil_Type                630000 non-null  object
 2   Soil_pH                  630000 non-null  float64
 3   Soil_Moisture            630000 non-null  float64
 4   Organic_Carbon           630000 non-null  float64
 5   Electrical_Conductivity  630000 non-null  float64
 6   Temperature_C            630000 non-null  float64
 7   Humidity                 630000 non-null  float64
 8   Rainfall_mm              630000 non-null  float64
 9   Sunlight_Hours           630000 non-null  float64
 10  Wind_Speed_kmh           630000 non-null  float64
 11  Crop_Type                630000 non-null  object
 12  Crop_Growth_Stage        630000 non-null  object
 13  Season                   630000 non-null  object
 14  Irrigation_Type          630000 non-null  object
 15  Water_Source             630000 non-null  object
 16  Field_Area_hectare       630000 non-null  float64
 17  Mulching_Used            630000 non-null  object
 18  Previous_Irrigation_mm   630000 non-null  float64
 19  Region                   630000 non-null  object
 20  Irrigation_Need          630000 non-null  object
dtypes: float64(11), int64(1), object(9)
memory usage: 100.9+ MB

In [ ]:
df_train.describe()

,id,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,6.482497,37.304482,0.922858,1.744605,26.998166,61.563180,1462.207566,7.513382,10.375394,7.517745,62.318177
std,181865.479132,0.922504,16.377082,0.365808,0.952321,8.623621,19.708152,612.989738,1.999322,5.689458,4.218124,34.246939
min,0.000000,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,157499.750000,5.690000,23.340000,0.610000,0.930000,19.517500,45.390000,954.570000,5.760000,5.280000,3.880000,33.140000
50%,314999.500000,6.440000,37.750000,0.910000,1.740000,26.960000,61.650000,1467.160000,7.580000,10.480000,7.380000,61.150000
75%,472499.250000,7.270000,51.270000,1.220000,2.580000,34.540000,79.120000,2054.280000,9.250000,15.430000,11.140000,92.690000
max,629999.000000,8.200000,64.990000,1.600000,3.500000,42.000000,94.990000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [25]:
df_train.select_dtypes(include=['object']).columns

Index(['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
       'Irrigation_Type', 'Water_Source', 'Mulching_Used', 'Region',
       'Irrigation_Need'],
      dtype='object')

In [48]:
df_test.select_dtypes(include=['object']).columns

Index(['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
       'Irrigation_Type', 'Water_Source', 'Mulching_Used', 'Region'],
      dtype='object')

In [26]:
df_ordinal = df_train[['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
       'Irrigation_Type', 'Water_Source', 'Mulching_Used', 'Region',
       'Irrigation_Need']]

In [7]:
df_ordinal

,Soil_Type,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Mulching_Used,Region,Irrigation_Need
0,Loamy,Sugarcane,Sowing,Zaid,Drip,Rainwater,No,East,Low
1,Clay,Wheat,Vegetative,Kharif,Rainfed,River,Yes,South,Low
2,Clay,Rice,Vegetative,Kharif,Sprinkler,Reservoir,Yes,North,Low
3,Sandy,Wheat,Flowering,Kharif,Canal,River,Yes,South,Medium
4,Clay,Wheat,Sowing,Rabi,Canal,River,No,South,Low
...,...,...,...,...,...,...,...,...,...
629995,Clay,Rice,Sowing,Kharif,Sprinkler,River,No,South,Medium
629996,Clay,Sugarcane,Vegetative,Kharif,Drip,Groundwater,Yes,Central,Medium
629997,Clay,Potato,Vegetative,Zaid,Canal,Reservoir,Yes,South,High
629998,Clay,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,Yes,East,Low
629999,Loamy,Maize,Harvest,Kharif,Drip,Reservoir,No,West,Low

In [27]:
for col in df_ordinal.columns:
    print(f"Kolom: {col}")
    print(df_ordinal[[col]].value_counts())
    print("-"*50)

Kolom: Soil_Type
Soil_Type
Sandy        166509
Clay         158470
Loamy        156455
Silt         148566
Name: count, dtype: int64
--------------------------------------------------
Kolom: Crop_Type
Crop_Type
Sugarcane    108910
Rice         106697
Cotton       104645
Maize        104274
Wheat        103005
Potato       102469
Name: count, dtype: int64
--------------------------------------------------
Kolom: Crop_Growth_Stage
Crop_Growth_Stage
Harvest              167689
Flowering            157563
Vegetative           157246
Sowing               147502
Name: count, dtype: int64
--------------------------------------------------
Kolom: Season
Season
Kharif    216561
Rabi      208033
Zaid      205406
Name: count, dtype: int64
--------------------------------------------------
Kolom: Irrigation_Type
Irrigation_Type
Canal              161901
Sprinkler          161400
Rainfed            155607
Drip               151092
Name: count, dtype: int64
--------------------------------------------------
Kolom: Water_Source
Water_Source
Reservoir       162994
River           159819
Groundwater     154155
Rainwater       153032
Name: count, dtype: int64
--------------------------------------------------
Kolom: Mulching_Used
Mulching_Used
No               316453
Yes              313547
Name: count, dtype: int64
--------------------------------------------------
Kolom: Region
Region
South      134809
West       131189
East       126163
Central    123712
North      114127
Name: count, dtype: int64
--------------------------------------------------
Kolom: Irrigation_Need
Irrigation_Need
Low                369917
Medium             239074
High                21009
Name: count, dtype: int64
--------------------------------------------------

In [28]:
df_ordinal = df_train[['Mulching_Used','Irrigation_Need']]

In [10]:
df_ordinal

       Mulching_Used Irrigation_Need
0                 No             Low
1                Yes             Low
2                Yes             Low
3                Yes          Medium
4                 No             Low
...              ...             ...
629995            No          Medium
629996           Yes          Medium
629997           Yes            High
629998           Yes             Low
629999            No             Low

[630000 rows x 2 columns]

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_train['Mulching_Used'] = le.fit_transform(df_train['Mulching_Used'])

In [50]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_test['Mulching_Used'] = le.fit_transform(df_test['Mulching_Used'])

In [12]:
df_train

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,0,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,1,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,1,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,1,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,0,93.19,South,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,...,Rice,Sowing,Kharif,Sprinkler,River,4.35,0,118.36,South,Medium
629996,629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,...,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,1,40.75,Central,Medium
629997,629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,...,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,1,2.62,South,High
629998,629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,...,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,1,90.00,East,Low
629999,629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,...,Maize,Harvest,Kharif,Drip,Reservoir,3.80,0,112.93,West,Low

In [30]:
mapping = {
    'Low': 0,
    'Medium': 1,
    'High': 2
}

df_train['Irrigation_Need'] = df_train['Irrigation_Need'].map(mapping)

In [49]:
mapping = {
    'Low': 0,
    'Medium': 1,
    'High': 2
}

df_test['Irrigation_Need'] = df_test['Irrigation_Need'].map(mapping)

KeyError: 'Irrigation_Need'

In [ ]:
df_train

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,0,112.16,East,0
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,1,47.16,South,0
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,1,110.38,North,0
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,1,53.85,South,1
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,0,93.19,South,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,...,Rice,Sowing,Kharif,Sprinkler,River,4.35,0,118.36,South,1
629996,629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,...,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,1,40.75,Central,1
629997,629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,...,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,1,2.62,South,2
629998,629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,...,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,1,90.00,East,0
629999,629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,...,Maize,Harvest,Kharif,Drip,Reservoir,3.80,0,112.93,West,0

In [31]:
df_train.select_dtypes(include=['object']).columns

Index(['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
       'Irrigation_Type', 'Water_Source', 'Region'],
      dtype='object')

In [32]:
cols = ['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
       'Irrigation_Type', 'Water_Source', 'Region']
df_train = pd.get_dummies(df_train, columns=cols, drop_first=True, dtype = int)

In [51]:
cols = ['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
       'Irrigation_Type', 'Water_Source', 'Region']
df_test = pd.get_dummies(df_test, columns=cols, drop_first=True, dtype = int)

In [33]:
df_train.head()

,id,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,...,Irrigation_Type_Drip,Irrigation_Type_Rainfed,Irrigation_Type_Sprinkler,Water_Source_Rainwater,Water_Source_Reservoir,Water_Source_River,Region_East,Region_North,Region_South,Region_West
0,0,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,...,1,0,0,1,0,0,1,0,0,0
1,1,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,...,0,1,0,0,0,1,0,0,1,0
2,2,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,...,0,0,1,0,1,0,0,1,0,0
3,3,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,...,0,0,0,0,0,1,0,0,1,0
4,4,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,...,0,0,0,0,0,1,0,0,1,0

In [35]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 37 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            630000 non-null  int64
 1   Soil_pH                       630000 non-null  float64
 2   Soil_Moisture                 630000 non-null  float64
 3   Organic_Carbon                630000 non-null  float64
 4   Electrical_Conductivity       630000 non-null  float64
 5   Temperature_C                 630000 non-null  float64
 6   Humidity                      630000 non-null  float64
 7   Rainfall_mm                   630000 non-null  float64
 8   Sunlight_Hours                630000 non-null  float64
 9   Wind_Speed_kmh                630000 non-null  float64
 10  Field_Area_hectare            630000 non-null  float64
 11  Mulching_Used                 630000 non-null  int64
 12  Previous_Irrigation_mm        630000 non-null  float64
 13  Irrigation_Need               630000 non-null  int64
 14  Soil_Type_Loamy               630000 non-null  int64
 15  Soil_Type_Sandy               630000 non-null  int64
 16  Soil_Type_Silt                630000 non-null  int64
 17  Crop_Type_Maize               630000 non-null  int64
 18  Crop_Type_Potato              630000 non-null  int64
 19  Crop_Type_Rice                630000 non-null  int64
 20  Crop_Type_Sugarcane           630000 non-null  int64
 21  Crop_Type_Wheat               630000 non-null  int64
 22  Crop_Growth_Stage_Harvest     630000 non-null  int64
 23  Crop_Growth_Stage_Sowing      630000 non-null  int64
 24  Crop_Growth_Stage_Vegetative  630000 non-null  int64
 25  Season_Rabi                   630000 non-null  int64
 26  Season_Zaid                   630000 non-null  int64
 27  Irrigation_Type_Drip          630000 non-null  int64
 28  Irrigation_Type_Rainfed       630000 non-null  int64
 29  Irrigation_Type_Sprinkler     630000 non-null  int64
 30  Water_Source_Rainwater        630000 non-null  int64
 31  Water_Source_Reservoir        630000 non-null  int64
 32  Water_Source_River            630000 non-null  int64
 33  Region_East                   630000 non-null  int64
 34  Region_North                  630000 non-null  int64
 35  Region_South                  630000 non-null  int64
 36  Region_West                   630000 non-null  int64
dtypes: float64(11), int64(26)
memory usage: 177.8 MB

In [34]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

from xgboost import XGBClassifier

In [37]:
X = df_train.drop(columns=['Irrigation_Need'])  # ganti 'target' sesuai punyamu
y = df_train['Irrigation_Need']

In [38]:
num_cols = X.select_dtypes(include='number').columns
cat_cols = X.select_dtypes(exclude='number').columns

In [39]:
numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [40]:
preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, num_cols),
    ('cat', categorical_pipeline, cat_cols)
])

In [41]:
model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

In [42]:
pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', model)
])

In [43]:
pipeline.fit(X, y)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['id', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm',
       'Sunlight_Hours', 'Wind_Speed_kmh', 'Field_Area_hectare',
       'Mulching_Used', 'Previous_Irrigation_m...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [44]:
df_test = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e4/test.csv')

In [52]:
preds = pipeline.predict(df_test)

In [53]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 36 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            270000 non-null  int64
 1   Soil_pH                       270000 non-null  float64
 2   Soil_Moisture                 270000 non-null  float64
 3   Organic_Carbon                270000 non-null  float64
 4   Electrical_Conductivity       270000 non-null  float64
 5   Temperature_C                 270000 non-null  float64
 6   Humidity                      270000 non-null  float64
 7   Rainfall_mm                   270000 non-null  float64
 8   Sunlight_Hours                270000 non-null  float64
 9   Wind_Speed_kmh                270000 non-null  float64
 10  Field_Area_hectare            270000 non-null  float64
 11  Mulching_Used                 270000 non-null  int64
 12  Previous_Irrigation_mm        270000 non-null  float64
 13  Soil_Type_Loamy               270000 non-null  int64
 14  Soil_Type_Sandy               270000 non-null  int64
 15  Soil_Type_Silt                270000 non-null  int64
 16  Crop_Type_Maize               270000 non-null  int64
 17  Crop_Type_Potato              270000 non-null  int64
 18  Crop_Type_Rice                270000 non-null  int64
 19  Crop_Type_Sugarcane           270000 non-null  int64
 20  Crop_Type_Wheat               270000 non-null  int64
 21  Crop_Growth_Stage_Harvest     270000 non-null  int64
 22  Crop_Growth_Stage_Sowing      270000 non-null  int64
 23  Crop_Growth_Stage_Vegetative  270000 non-null  int64
 24  Season_Rabi                   270000 non-null  int64
 25  Season_Zaid                   270000 non-null  int64
 26  Irrigation_Type_Drip          270000 non-null  int64
 27  Irrigation_Type_Rainfed       270000 non-null  int64
 28  Irrigation_Type_Sprinkler     270000 non-null  int64
 29  Water_Source_Rainwater        270000 non-null  int64
 30  Water_Source_Reservoir        270000 non-null  int64
 31  Water_Source_River            270000 non-null  int64
 32  Region_East                   270000 non-null  int64
 33  Region_North                  270000 non-null  int64
 34  Region_South                  270000 non-null  int64
 35  Region_West                   270000 non-null  int64
dtypes: float64(11), int64(25)
memory usage: 74.2 MB

In [47]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 37 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            630000 non-null  int64
 1   Soil_pH                       630000 non-null  float64
 2   Soil_Moisture                 630000 non-null  float64
 3   Organic_Carbon                630000 non-null  float64
 4   Electrical_Conductivity       630000 non-null  float64
 5   Temperature_C                 630000 non-null  float64
 6   Humidity                      630000 non-null  float64
 7   Rainfall_mm                   630000 non-null  float64
 8   Sunlight_Hours                630000 non-null  float64
 9   Wind_Speed_kmh                630000 non-null  float64
 10  Field_Area_hectare            630000 non-null  float64
 11  Mulching_Used                 630000 non-null  int64
 12  Previous_Irrigation_mm        630000 non-null  float64
 13  Irrigation_Need               630000 non-null  int64
 14  Soil_Type_Loamy               630000 non-null  int64
 15  Soil_Type_Sandy               630000 non-null  int64
 16  Soil_Type_Silt                630000 non-null  int64
 17  Crop_Type_Maize               630000 non-null  int64
 18  Crop_Type_Potato              630000 non-null  int64
 19  Crop_Type_Rice                630000 non-null  int64
 20  Crop_Type_Sugarcane           630000 non-null  int64
 21  Crop_Type_Wheat               630000 non-null  int64
 22  Crop_Growth_Stage_Harvest     630000 non-null  int64
 23  Crop_Growth_Stage_Sowing      630000 non-null  int64
 24  Crop_Growth_Stage_Vegetative  630000 non-null  int64
 25  Season_Rabi                   630000 non-null  int64
 26  Season_Zaid                   630000 non-null  int64
 27  Irrigation_Type_Drip          630000 non-null  int64
 28  Irrigation_Type_Rainfed       630000 non-null  int64
 29  Irrigation_Type_Sprinkler     630000 non-null  int64
 30  Water_Source_Rainwater        630000 non-null  int64
 31  Water_Source_Reservoir        630000 non-null  int64
 32  Water_Source_River            630000 non-null  int64
 33  Region_East                   630000 non-null  int64
 34  Region_North                  630000 non-null  int64
 35  Region_South                  630000 non-null  int64
 36  Region_West                   630000 non-null  int64
dtypes: float64(11), int64(26)
memory usage: 177.8 MB

In [55]:
preds

array([0, 0, 0, ..., 1, 0, 1])

In [64]:
df_submit = pd.DataFrame({
    'id': df_test['id'],   # pastikan nama kolom sesuai (Id / id)
    'Irrigation_Need': preds        # hasil prediksi model
})

In [60]:
df_submit

            id  Irrigation_Need
0       630000                0
1       630001                0
2       630002                0
3       630003                0
4       630004                0
...        ...              ...
269995  899995                1
269996  899996                0
269997  899997                1
269998  899998                0
269999  899999                1

[270000 rows x 2 columns]

In [66]:
df_submit.to_csv('submission.csv', index=False)

In [65]:
reverse_mapping = {
    0: 'Low',
    1: 'Medium',
    2: 'High'
}

df_submit['Irrigation_Need'] = df_submit['Irrigation_Need'].map(reverse_mapping)

In [68]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.1 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [69]:
import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

In [70]:
X = df_train.drop(columns=['Irrigation_Need'])  # ganti sesuai target kamu
y = df_train['Irrigation_Need']

In [71]:
num_cols = X.select_dtypes(include='number').columns
cat_cols = X.select_dtypes(exclude='number').columns

In [72]:
numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, num_cols),
    ('cat', categorical_pipeline, cat_cols)
])

In [73]:
models = {
    "RandomForest": RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric='logloss',
        random_state=42
    ),

    "LightGBM": LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        random_state=42
    ),

    "CatBoost": CatBoostClassifier(
        iterations=300,
        learning_rate=0.05,
        depth=6,
        verbose=0,
        random_state=42
    )
}

In [74]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = {}

for name, model in models.items():

    pipeline = Pipeline([
        ('preprocessing', preprocessor),
        ('model', model)
    ])

    scores = cross_val_score(
        pipeline,
        X,
        y,
        cv=kfold,
        scoring='accuracy',  # bisa diganti roc_auc / f1
        n_jobs=-1
    )

    results[name] = scores

    print(f"{name}")
    print(f"Mean Accuracy: {scores.mean():.4f}")
    print(f"Std: {scores.std():.4f}")
    print("-"*40)

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

RandomForest
Mean Accuracy: 0.9851
Std: 0.0002
----------------------------------------
XGBoost
Mean Accuracy: 0.9844
Std: 0.0003
----------------------------------------
LightGBM
Mean Accuracy: 0.9843
Std: 0.0001
----------------------------------------

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

CatBoost
Mean Accuracy: 0.9845
Std: 0.0005
----------------------------------------

In [75]:
result_df = pd.DataFrame(results)
print(result_df.describe().T)

              count      mean       std       min       25%       50%  \
RandomForest    5.0  0.985129  0.000264  0.984833  0.985016  0.985087
XGBoost         5.0  0.984443  0.000319  0.984008  0.984270  0.984437
LightGBM        5.0  0.984257  0.000166  0.984087  0.984111  0.984270
CatBoost        5.0  0.984494  0.000571  0.983603  0.984341  0.984603

                   75%       max
RandomForest  0.985159  0.985548
XGBoost       0.984738  0.984762
LightGBM      0.984325  0.984492
CatBoost      0.984817  0.985103

In [76]:
from sklearn.ensemble import VotingClassifier
from sklearn.pipeline import Pipeline

voting_model = VotingClassifier(
    estimators=[
        ('rf', models['RandomForest']),
        ('xgb', models['XGBoost']),
        ('lgbm', models['LightGBM']),
        ('cat', models['CatBoost'])
    ],
    voting='soft'  # pakai probabilitas (lebih bagus)
)

pipeline_voting = Pipeline([
    ('preprocessing', preprocessor),
    ('model', voting_model)
])

In [77]:
pipeline_voting.fit(X, y)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042088 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2972
[LightGBM] [Info] Number of data points in the train set: 630000, number of used features: 36
[LightGBM] [Info] Start training from score -0.532441
[LightGBM] [Info] Start training from score -0.968947
[LightGBM] [Info] Start training from score -3.400769

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['id', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm',
       'Sunlight_Hours', 'Wind_Speed_kmh', 'Field_Area_hectare',
       'Mulching_Used', 'Previous_Irrigation_m...
                                                             max_depth=6,
                                                             max_leaves=None,
                                                             min_child_weight=None,
                                                             missing=nan,
                                                             monotone_constraints=None,
                                                             multi_strategy=None,
                                                             n_estimators=300,
                                                             n_jobs=None,
                                                             num_parallel_tree=None, ...)),
                                              ('lgbm',
                                               LGBMClassifier(learning_rate=0.05,
                                                              n_estimators=300,
                                                              random_state=42)),
                                              ('cat',
                                               CatBoostClassifier(depth=6, iterations=300, learning_rate=0.05, random_state=42, verbose=0))],
                                  voting='soft'))])

In [78]:
preds = pipeline_voting.predict(df_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [79]:
df_submit = pd.DataFrame({
    'id': df_test['id'],   # pastikan nama kolom sesuai (Id / id)
    'Irrigation_Need': preds        # hasil prediksi model
})

In [80]:
reverse_mapping = {
    0: 'Low',
    1: 'Medium',
    2: 'High'
}

df_submit['Irrigation_Need'] = df_submit['Irrigation_Need'].map(reverse_mapping)

In [81]:
df_submit.to_csv('submission_ensemble.csv', index=False)